# Generated by Django 4.2.19 on 2025-02-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("recruitment", "0004_auto_20220526_0617"),
        ("recruitment", "0005_instructorrecruitment_priority"),
        ("recruitment", "0006_remove_instructorrecruitmentsignup_rq_jobs"),
    ]

    dependencies = [
        ("recruitment", "0003_auto_20220220_1514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorrecruitmentsignup",
            name="recruitment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signups",
                to="recruitment.instructorrecruitment",
            ),
        ),
        migrations.AddField(
            model_name="instructorrecruitment",
            name="priority",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Low"), (2, "Medium"), (3, "High")],
                help_text="If no priority is selected, automated priority will be calculated based on the days to start"
                " of the event.",
                null=True,
            ),
        ),
    ]
