# Generated by Django 2.2.24 on 2021-08-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autoemails", "0015_auto_20210405_1920"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rqjob",
            name="recipients",
            field=models.TextField(blank=True, default="", verbose_name="Mail recipients"),
        ),
    ]
