# Generated by Django 2.2.27 on 2022-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autoemails", "0017_auto_20210901_0226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="action",
            field=models.CharField(
                choices=[
                    ("new-instructor", "Instructor is added to the workshop"),
                    ("new-supporting-instructor", "Supporting Instructor is added to the workshop"),
                    ("week-after-workshop-completion", "7 days past the end date of an active workshop"),
                    ("self-organised-request-form", "A new event is created from Self-Organised Request Form"),
                    ("instructors-host-introduction", "Introduction of instructors and host (centr. org. workshop)"),
                    ("ask-for-website", "Website URL is missing"),
                    ("recruit-helpers", "Recruit helpers"),
                    ("workshop-request-response1", "Response to Workshop Request 1"),
                    ("workshop-request-response2", "Response to Workshop Request 2"),
                    ("workshop-request-response3", "Response to Workshop Request 3"),
                    ("consent-required", "There is a new or updated term added that the users should consent to"),
                    ("profile-update", "Reminder to for the user to update the information in their profile."),
                ],
                max_length=50,
                verbose_name="Action",
            ),
        ),
    ]
