# Generated by Django 4.2.20 on 2025-07-13 18:35

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("workshops", "0281_curriculumtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("individual", "individual"),
                            ("organisation", "organisation"),
                            ("consortium", "consortium"),
                        ],
                        max_length=30,
                    ),
                ),
                ("generic_relation_pk", models.PositiveBigIntegerField()),
                (
                    "generic_relation_content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(("app_label", "workshops"), ("model", "person")),
                            models.Q(("app_label", "workshops"), ("model", "organization")),
                            models.Q(("app_label", "fiscal"), ("model", "consortium")),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Benefit",
            fields=[
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("allocation", models.PositiveIntegerField()),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="offering.account")),
                (
                    "curriculum",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="workshops.curriculum"
                    ),
                ),
                (
                    "event_category",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="offering.eventcategory"),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="workshops.membership"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountOwner",
            fields=[
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "permission_type",
                    models.CharField(
                        choices=[("account_contact", "account_contact"), ("billing_contact", "billing_contact")],
                        max_length=30,
                    ),
                ),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="offering.account")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("generic_relation_content_type", "generic_relation_pk"), name="unique_account_relation"
            ),
        ),
    ]
