# Generated by Django 4.2.23 on 2025-09-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offering", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="benefit",
            name="credits",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
