site_name: AMY documentation
repo_url: https://github.com/carpentries/amy/
edit_uri: 'edit/develop/docs/'

theme: readthedocs
nav:
    - 'Home': 'index.md'
    - 'For AMY Administrators':
        - 'Users Guide': 'users_guide/index.md'
        - 'Database Structure': 'amy_database_structure.md'
    - 'For AMY Developers':
        - 'Design': 'design/index.md'
        - 'Application design': 'design/application_design.md'
        - 'Database models': 'design/database_models.md'
        - 'Model versioning': 'design/model_versioning.md'
        - 'Template Hierarchy': 'design/template_hierarchy.md'
        - 'Server Infrastructure': 'design/server_infrastructure.md'
        - 'Procedures': 'procedures.md'
        - 'Sending Mails': 'sending_mails.md'
        - 'Releases': 'releases'
    - 'About The Carpentries':
        - 'The Carpentries': 'https://carpentries.org'
        - 'Data Carpentry': 'https://datacarpentry.org/'
        - 'Library Carpentry': 'https://librarycarpentry.org/'
        - 'Software Carpentry': 'https://software-carpentry.org/'
        - 'AMY': 'https://amy.carpentries.org'


markdown_extensions:
    - toc:
        permalink: 

extra_css: [extra.css]
