site_name: AMY documentation
repo_url: https://github.com/carpentries/amy/
edit_uri: 'edit/develop/docs/'

theme: readthedocs
nav:
    - 'Home': 'index.md'
    - 'For AMY Administrators':
        - 'Users Guide': 'users_guide/index.md'
        - 'Database Structure': 'amy_database_structure.md'
    - 'For AMY Developers':
        - 'Design': 'design/index.md'
        - 'Application design': 'design/application_design.md'
        - 'Database models': 'design/database_models.md'
        - 'Model versioning': 'design/model_versioning.md'
        - 'Templates': 'design/template_hierarchy.md'
        - 'Server Infrastructure': 'design/server_infrastructure.md'
        - 'Procedures': 'procedures.md'
        - 'Sending Mails': 'sending_mails.md'
        - 'Releases': './releases/README.md'
        - 'Projects':
          - 'Projects': './design/projects/README.md'
          - 'Automated emails': './design/projects/2019_automated_emails.md'
          - 'Memberships': './design/projects/2021_memberships.md'
          - 'Consents': './design/projects/2021_consents.md'
          - 'Profile Archival': './design/projects/2021_profile_archival.md'
          - 'Community Roles': './design/projects/2021_community_roles.md'
          - 'Instructor Selection': './design/projects/2021_instructor_selection.md'
          - 'Single Instructor Badge': './design/projects/2021_single_instructor_badge.md'
    - 'About The Carpentries':
        - 'The Carpentries': 'https://carpentries.org'
        - 'Data Carpentry': 'https://datacarpentry.org/'
        - 'Library Carpentry': 'https://librarycarpentry.org/'
        - 'Software Carpentry': 'https://software-carpentry.org/'
        - 'AMY': 'https://amy.carpentries.org'


markdown_extensions:
    - toc:
        permalink: 

extra_css: [extra.css]
