# Generated by Django 4.2.16 on 2025-02-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0006_alter_emailtemplate_body_alter_emailtemplate_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledemail",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="emails.emailtemplate",
                verbose_name="Linked template",
            ),
        ),
    ]
