# Generated by Django 4.2.17 on 2025-02-23 11:51

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_alter_scheduledemail_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('s3_path', models.CharField(help_text='Path inside the bucket', max_length=200)),
                ('s3_bucket', models.CharField(blank=True, max_length=200)),
                ('presigned_url', models.CharField(blank=True, default='', max_length=5000)),
                ('presigned_url_expiration', models.DateTimeField(null=True)),
                (
                    'email',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='attachments',
                        to='emails.scheduledemail',
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
