# Generated by Django 1.9.2 on 2016-02-29 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0079_eventsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="awarded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="awarded_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
