# Generated by Django 1.9.2 on 2016-03-26 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0084_lowercase_emails"),
        ("workshops", "0084_auto_20160326_0402"),
    ]

    operations = []
