# Generated by Django 1.9.5 on 2016-06-08 16:10

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def forward(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="administrators")


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0096_change_help_text_in_training_request"),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop),
    ]
