# Generated by Django 1.9.5 on 2016-06-18 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0100_merge"),
        ("workshops", "0099_dcselforganizedeventrequest"),
    ]

    operations = []
