# Generated by Django 1.9.12 on 2016-12-18 10:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0122_auto_20161101_1441"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="awarded",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
