# Generated by Django 4.2.19 on 2025-02-06 05:37

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("workshops", "0211_task_rq_jobs"),
        ("workshops", "0273_remove_task_rq_jobs"),
    ]

    dependencies = [
        ("workshops", "0210_auto_20200124_1939"),
    ]

    operations = []
