# Generated by Django 4.2.19 on 2025-02-06 05:38

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("workshops", "0221_workshoprequest_rq_jobs"),
        ("workshops", "0275_remove_workshoprequest_rq_jobs"),
    ]

    dependencies = [
        ("workshops", "0221_auto_20201025_1113"),
    ]

    operations = []
