# Generated by Django 2.2.24 on 2021-08-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0249_auto_20210709_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshoprequest",
            name="preferred_dates",
            field=models.DateField(
                blank=True,
                help_text="Please select your preferred first day for the workshop. If you do not have exact dates or"
                " are interested in an alternative schedule, please indicate so below. Because we need to coordinate"
                " with instructors, a minimum of 2-3 months lead time is required for workshop planning.<br>The "
                "preferred dates are not a guarantee. We do our best to schedule your workshop for the dates that "
                "you have requested, however, a high volume of workshops on a given date may prevent us from "
                "fulfilling your request. Please prepare alternative dates in the event that we can not accommodate"
                " your request.",
                null=True,
                verbose_name="Preferred dates",
            ),
        ),
    ]
