# Generated by Django 4.2.19 on 2025-02-06 05:38

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("workshops", "0251_person_rq_jobs"),
        ("workshops", "0276_remove_person_rq_jobs"),
    ]

    dependencies = [
        ("workshops", "0250_auto_20210807_1951"),
    ]

    operations = []
