# Generated by Django 2.2.24 on 2021-09-01 02:26

####################################################################
#  N O T E:  this migration is legacy and references removed code  #
####################################################################

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0250_auto_20210807_1951"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="rq_jobs",
            field=models.ManyToManyField(
                blank=True,
                help_text="This should be filled out by AMY itself.",
                to="autoemails.RQJob",
                verbose_name="Related Redis Queue jobs",
            ),
        ),
    ]
