# Generated by Django 2.2.24 on 2021-12-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0251_person_rq_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshoprequest",
            name="administrative_fee",
            field=models.CharField(
                choices=[
                    (
                        "nonprofit",
                        "I am with a government site, university, or other nonprofit. I understand the workshop fee as"
                        " listed on The Carpentries website and agree to follow through on The Carpentries invoicing"
                        " process.",
                    ),
                    (
                        "forprofit",
                        "I am with a corporate or for-profit site. I understand the costs for for-profit organisations"
                        " are four times the price for not-for-profit organisations.",
                    ),
                    (
                        "member",
                        "I am with a Member organisation so the workshop fee does not apply (instructor travel costs"
                        " will still apply for in-person workshops).",
                    ),
                    (
                        "waiver",
                        "I am requesting financial support for the workshop fee (instructor travel costs will still"
                        " apply for in-person workshops)",
                    ),
                ],
                default=None,
                help_text="<a href='https://carpentries.org/workshops/#workshop-cost' target='_blank' rel='noreferrer"
                " nofollow'>The Carpentries website workshop fee listing.</a>",
                max_length=20,
                verbose_name="Which of the following applies to your payment for the administrative fee?",
            ),
        ),
    ]
