# Generated by Django 3.2.14 on 2022-08-07 10:19

from django.db import migrations

import src.workshops.fields


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0253_curriculum_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingrequest",
            name="github",
            field=src.workshops.fields.NullableGithubUsernameField(
                blank=True,
                default="",
                help_text="Please put only a single username here. After your application has been accepted, you will"
                " be able to use your GitHub username to log in to our database to view your profile.",
                max_length=39,
                null=True,
                verbose_name="GitHub username",
            ),
        ),
    ]
