# Generated by Django 3.2.18 on 2023-02-20 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consents", "0005_auto_20210411_2325"),
        ("workshops", "0255_auto_20230207_1818"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="data_privacy_agreement",
        ),
        migrations.RemoveField(
            model_name="person",
            name="lesson_publication_consent",
        ),
        migrations.RemoveField(
            model_name="person",
            name="may_contact",
        ),
        migrations.RemoveField(
            model_name="person",
            name="publish_profile",
        ),
    ]
