# Generated by Django 3.2.18 on 2023-04-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0256_auto_20230220_2051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="variant",
            field=models.CharField(
                choices=[
                    ("partner", "Partner"),
                    ("affiliate", "Affiliate"),
                    ("sponsor", "Sponsor"),
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("platinum", "Platinum"),
                    ("titanium", "Titanium"),
                    ("alacarte", "A la carte"),
                ],
                max_length=40,
            ),
        ),
    ]
