# Generated by Django 3.2.20 on 2023-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0266_add_member_code_and_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingrequest",
            name="nonprofit_teaching_experience",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Provide details or leave blank if this doesn't apply to you.",
                max_length=255,
                verbose_name="I have been an active contributor to other volunteer or non-profit groups with "
                "significant teaching or training components.",
            ),
        ),
        migrations.AlterField(
            model_name="trainingrequest",
            name="previous_experience_explanation",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Description of your previous experience in teaching",
            ),
        ),
        migrations.AlterField(
            model_name="trainingrequest",
            name="previous_training_explanation",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Description of your previous training in teaching",
            ),
        ),
    ]
