# Generated by Django 3.2.20 on 2023-11-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0268_trainingrequest_eventbrite_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="agreement_link",
            field=models.URLField(
                default="",
                help_text="Link to member agreement document or folder in Google Drive",
                verbose_name="Link to member agreement",
            ),
        ),
    ]
