# Generated by Django 4.2.11 on 2024-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0269_alter_membership_agreement_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="affiliated_organizations",
            field=models.ManyToManyField(blank=True, to="workshops.organization"),
        ),
    ]
