# Generated by Django 4.2.16 on 2024-12-30 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0271_alter_workshoprequest_administrative_fee"),
    ]

    operations = [
        # #2044
        migrations.AlterField(
            model_name="event",
            name="host",
            field=models.ForeignKey(
                help_text="The institution where the workshop is taking place "
                "(or would take place for online workshops).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hosted_events",
                to="workshops.organization",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                help_text="The membership this workshop should count towards.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workshops.membership",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="sponsor",
            field=models.ForeignKey(
                help_text="The institution responsible for organizing and funding the workshop "
                "(often the same as Host).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sponsored_events",
                to="workshops.organization",
            ),
        ),
        # #2094
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("event", "person", "role")},
        ),
        migrations.RemoveField(
            model_name="task",
            name="title",
        ),
        migrations.RemoveField(
            model_name="task",
            name="url",
        ),
        # #2726
        migrations.AddField(
            model_name="person",
            name="bluesky",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="BlueSky username",
            ),
        ),
    ]
