# Generated by Django 4.2.20 on 2025-03-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0277_merge_20250206_0536"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="rolled_to_membership",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rolled_from_membership",
                to="workshops.membership",
            ),
        ),
    ]
