# Generated by Django 4.2.25 on 2025-10-12 17:01

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0283_event_allocated_benefit_task_allocated_benefit"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="timezone",
            field=models.CharField(blank=True, default="", help_text="Override timezone of the airport."),
        ),
        migrations.AlterField(
            model_name="person",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="", help_text="Override country of the airport.", max_length=2
            ),
        ),
    ]
