# Generated by Django 4.2.25 on 2025-10-12 17:01

import airportsdata
import django_countries.fields
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

IATA_AIRPORTS = airportsdata.load("IATA")


def migrate_airport_model_to_airportdata_table(apps: StateApps, schemat_editor: BaseDatabaseSchemaEditor) -> None:
    Person = apps.get_model("workshops", "Person")
    for person in Person.objects.select_related("airport").all():
        if person.airport:
            if person.airport.iata not in IATA_AIRPORTS:
                print(f"Error: Airport {person.airport.iata} not found in airportdata")
                continue

            airport_iata = IATA_AIRPORTS[person.airport.iata]
            person.airport_iata = person.airport.iata
            person.airport_country = airport_iata["country"]
            person.airport_lat = airport_iata["lat"]
            person.airport_lon = airport_iata["lon"]
            person.save()


def migrate_airportdata_table_to_airport_model(apps: StateApps, schemat_editor: BaseDatabaseSchemaEditor) -> None:
    Airport = apps.get_model("workshops", "Airport")
    Person = apps.get_model("workshops", "Person")
    for person in Person.objects.all():
        if person.airport_iata:
            try:
                airport = IATA_AIRPORTS[person.airport_iata]
            except KeyError:
                print(f"Error: Airport {person.airport.iata} not found in airportdata")
                continue

            person.airport, _ = Airport.objects.get_or_create(
                iata=airport["iata"],
                defaults=dict(
                    fullname=airport["name"],
                    country=airport["country"],
                    latitude=airport["lat"],
                    longitude=airport["lon"],
                ),
            )
            person.save()


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0284_person_timezone_override_alter_person_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="airport_iata",
            field=models.CharField(
                max_length=10,
                null=False,
                blank=True,
                default="",
                help_text="Nearest major airport (IATA code: https://www.world-airport-codes.com/)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="airport_country",
            field=django_countries.fields.CountryField(
                blank=True, default="", help_text="Airport country (copied from airport data package)", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="airport_lat",
            field=models.FloatField(default=0.0, help_text="Airport latitude (copied from airport data package)"),
        ),
        migrations.AddField(
            model_name="person",
            name="airport_lon",
            field=models.FloatField(default=0.0, help_text="Airport longitude (copied from airport data package)"),
        ),
        migrations.RunPython(
            migrate_airport_model_to_airportdata_table,
            migrate_airportdata_table_to_airport_model,
        ),
        migrations.RemoveField(model_name="person", name="airport"),
    ]
