# Generated by Django 5.2.12 on 2026-03-04 17:39

from django.db import migrations, models

import src.workshops.fields


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0288_trainingrequest_airport_iata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="bluesky",
            field=src.workshops.fields.BlueSkyHandleField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="BlueSky username"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Primary email address, used for communication and as a login.",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Email address",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="mastodon",
            field=src.workshops.fields.MastodonURLField(
                blank=True, null=True, unique=True, verbose_name="Mastodon URL"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="orcid",
            field=src.workshops.fields.OrcidField(blank=True, default="", max_length=100, verbose_name="ORCID ID"),
        ),
    ]
