# Generated by Django 5.2.12 on 2026-03-07 17:50

import airportsdata
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

IATA_AIRPORTS = airportsdata.load("IATA")


def migrate_airport_model_to_airportdata_table(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Person = apps.get_model("workshops", "Person")
    for person in Person.objects.all():
        if person.airport_iata and person.airport_iata in IATA_AIRPORTS:
            airport_iata = IATA_AIRPORTS[person.airport_iata]
            person.airport_timezone = airport_iata["tz"]
            person.save()


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0290_alter_workshoprequest_member_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="airport_timezone",
            field=models.CharField(
                default="", help_text="Airport timezone (copied from airport data package)", blank=True
            ),
        ),
        migrations.RunPython(
            migrate_airport_model_to_airportdata_table,
        ),
    ]
