# Generated by Django 5.2.12 on 2026-03-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0291_person_airport_timezone_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingrequest",
            name="member_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you have been given a registration code through a Carpentries member or partner site or "
                "for a specific scheduled event, please enter it here:",
                max_length=100,
                verbose_name="Registration Code",
            ),
        ),
        migrations.AlterField(
            model_name="workshoprequest",
            name="administrative_fee",
            field=models.CharField(
                choices=[
                    (
                        "nonprofit",
                        "I am with a government site, university, or other nonprofit. I understand the workshop fee as "
                        "listed on The Carpentries website and agree to follow through on The Carpentries invoicing "
                        "process.",
                    ),
                    (
                        "forprofit",
                        "I am with a corporate or for-profit site. I understand the costs for for-profit organisations "
                        "are higher than the price for not-for-profit organisations, as listed on The Carpentries "
                        "website.",
                    ),
                    (
                        "member",
                        "I am with a Member or Partner organisation so the workshop fee does not apply (instructor "
                        "travel costs will still apply for in-person workshops).",
                    ),
                    (
                        "waiver",
                        "I am requesting financial support for the workshop fee (instructor travel costs will still "
                        "apply for in-person workshops)",
                    ),
                ],
                default=None,
                help_text="<b><a href='https://carpentries.org/workshops/#workshop-cost' target='_blank' "
                "rel='noreferrer nofollow'>The Carpentries website workshop fee listing.</a></b>",
                max_length=20,
                verbose_name="Which of the following applies to your payment for the administrative fee?",
            ),
        ),
        migrations.AlterField(
            model_name="workshoprequest",
            name="member_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you are affiliated with a Carpentries member or partner organization, please enter your "
                "registration code.",
                max_length=40,
                verbose_name="Registration code",
            ),
        ),
    ]
