# Generated by Django 5.2.13 on 2026-04-26 08:52

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0292_alter_trainingrequest_member_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="carpentry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SWC", "Software Carpentry"),
                    ("DC", "Data Carpentry"),
                    ("LC", "Library Carpentry"),
                    ("HPCC", "High Performance Computing Carpentry"),
                    ("", "unspecified / irrelevant"),
                ],
                default="",
                max_length=5,
                verbose_name="Which Carpentry does this curriculum belong to?",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text='Required in order for this event to be "published".<br />For Data, Library, Software, or High Performance Computing Carpentry workshops, always use the country of the host organisation. <br />For Instructor Training, use the country only for in-person events, and use <b>Online</b> for online events. <br />Be sure to use the <b>online tag</b> above for all online events.',  # noqa: E501
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workshoprequest",
            name="requested_workshop_types",
            field=models.ManyToManyField(
                help_text='If your learners are new to programming and primarily interested in working with data, Data Carpentry is likely the best choice. If your learners are interested in learning more about programming, including version control and automation, Software Carpentry is likely the best match. If your learners are people working in library and information related roles interested in learning data and software skills, Library Carpentry is the best choice. If your learners want to use high performance computing (HPC) systems for research, High Performance Computing Carpentry is likely the best match. Please visit the <a href="https://software-carpentry.org/lessons/">Software Carpentry lessons page</a>, <a href="http://www.datacarpentry.org/lessons/">Data Carpentry lessons page</a>, <a href="https://librarycarpentry.org/lessons/">Library Carpentry lessons page</a>, or the <a href="https://hpcccarpentry.org/lessons">High Performance Computing Carpentry lessons page</a> for more information about any of our lessons.<br>If you are not sure which workshop curriculum you would like to have taught, please complete the <a href=\'/forms/inquiry/\'>Workshop Inquiry Form</a>.',  # noqa: E501
                limit_choices_to={"active": True},
                to="workshops.curriculum",
                verbose_name="Which Carpentries workshop are you requesting?",
            ),
        ),
    ]
