# Generated by Django 5.2.14 on 2026-06-23 19:36

import django.db.models.deletion
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

INSTRUCTOR_TRAINING_BENEFIT_NAME = "Instructor Training"


def set_instructor_training(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Benefit = apps.get_model("offering", "Benefit")
    TrainingRequest = apps.get_model("workshops", "TrainingRequest")

    try:
        instructor_training_benefit = Benefit.objects.get(name=INSTRUCTOR_TRAINING_BENEFIT_NAME)
        TrainingRequest.objects.filter(benefit__isnull=True).update(benefit=instructor_training_benefit)
    except Benefit.DoesNotExist:
        print('ERROR: Benefit with name "Instructor Training" does not exist. The migration has not applied it.')


class Migration(migrations.Migration):
    dependencies = [
        ("offering", "0008_accountbenefit_check_partnership_discount"),
        ("workshops", "0294_hpcc_tag_and_curriculum"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrequest",
            name="benefit",
            field=models.ForeignKey(
                blank=False,
                default=None,
                limit_choices_to=models.Q(("active", True)),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="offering.benefit",
                verbose_name="What Carpentries offering are you signing up for?",
            ),
        ),
        migrations.RunPython(set_instructor_training, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="trainingrequest",
            name="eventbrite_url",
            field=models.URLField(
                blank=False,
                default="",
                help_text="If you are registering or have registered for an event, enter the URL of that event. "
                "You can find this on the registration page or in the confirmation email. "
                "If you have not yet registered for an event, leave this field blank.",
                verbose_name="Event registration URL",
            ),
        ),
        migrations.AlterField(
            model_name="trainingrequest",
            name="reason",
            field=models.TextField(verbose_name="Why do you want to attend this event?"),
        ),
    ]
