# Generated by Django 5.2.14 on 2026-07-02 19:05

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def set_training_event_category(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    EventCategory = apps.get_model("workshops", "EventCategory")
    Event = apps.get_model("workshops", "Event")

    try:
        training_event_category = EventCategory.objects.get(name="training")
        Event.objects.filter(event_category__isnull=True, tags__name__in=["TTT", "ITT", "CLDT", "ITB"]).update(
            event_category=training_event_category
        )
    except EventCategory.DoesNotExist:
        print('ERROR: Event category with name "training" does not exist. The migration has not applied it.')


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0295_trainingrequest_benefit"),
    ]

    operations = [
        migrations.RunPython(set_training_event_category, reverse_code=migrations.RunPython.noop),
    ]
