# Generated by Django 5.2.14 on 2026-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0296_set_training_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshoprequest",
            name="administrative_fee",
            field=models.CharField(
                choices=[
                    (
                        "nonprofit",
                        "I am with a government site, university, or other nonprofit. I understand the workshop fee as "
                        "listed on The Carpentries website and agree to follow through on The Carpentries invoicing "
                        "process.",
                    ),
                    (
                        "forprofit",
                        "I am with a corporate or for-profit site. I understand the costs for for-profit organisations "
                        "are higher than what is listed on The Carpentries website and will be discussed during the "
                        "scheduling process.",
                    ),
                    (
                        "member",
                        "I am with a Member or Partner organisation so the workshop fee does not apply (instructor "
                        "travel costs will still apply for in-person workshops).",
                    ),
                    (
                        "waiver",
                        "I am requesting financial support for the workshop fee (instructor travel costs will still "
                        "apply for in-person workshops)",
                    ),
                ],
                default=None,
                help_text="<b><a href='https://carpentries.org/support/pricing/' target='_blank' rel='noreferrer "
                "nofollow'>Please visit our website to see our current pricing.</a></b>",
                max_length=20,
                verbose_name="Which of the following applies to your payment for the administrative fee?",
            ),
        ),
    ]
