# Generated by Django 5.2.15 on 2026-07-26 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0297_alter_workshoprequest_administrative_fee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["family", "personal"],
                "permissions": [
                    ("can_access_restricted_API", "Can this user access the restricted API endpoints?"),
                    ("access_admin_dashboard", "Can access the admin dashboard"),
                    ("use_search", "Can use the global search and workshop-staff finder"),
                    ("view_changelog", "Can view the object changes log"),
                    ("view_reports", "Can view reports"),
                ],
            },
        ),
    ]
