# Generated by Django 5.2.15 on 2026-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0298_alter_person_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrequest",
            name="tasks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tasks this request was matched to.",
                related_name="training_requests",
                to="workshops.task",
                verbose_name="Linked training tasks",
            ),
        ),
    ]
