# Generated by Django 5.2.15 on 2026-08-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0298_alter_person_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrequest",
            name="task",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="Task created when this request was matched to a training.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workshops.task",
                verbose_name="Linked training task",
            ),
        ),
    ]
