# Generated by Django 4.2.23 on 2025-09-21 17:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offering", "0001_initial"),
        ("fiscal", "0002_consortium_partnershiptier_partnership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="benefit",
            name="credits",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AccountBenefitDiscount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountBenefit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("allocation", models.PositiveIntegerField()),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="offering.account")),
                ("benefit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="offering.benefit")),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="offering.accountbenefitdiscount",
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="workshops.curriculum"
                    ),
                ),
                (
                    "partnership",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="fiscal.partnership"
                    ),
                ),
                ("frozen", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
