# Generated by Django 4.2.23 on 2025-10-01 19:39

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from src.offering.models import Account as AccountModel


def create_accounts_for_organizations(apps: StateApps, schemat_editor: BaseDatabaseSchemaEditor) -> None:
    Organization = apps.get_model("workshops", "Organization")
    Account = apps.get_model("offering", "Account")
    ContentType = apps.get_model("contenttypes", "ContentType")
    organisation_ct = ContentType.objects.get_for_model(Organization)

    all_organisations = Organization.objects.all()
    for organisation in all_organisations:
        Account.objects.get_or_create(
            generic_relation_content_type=organisation_ct,
            generic_relation_pk=organisation.pk,
            defaults=dict(account_type=AccountModel.AccountTypeChoices.ORGANISATION),
        )


class Migration(migrations.Migration):
    """Data migration that creates account for every organization in the system."""

    dependencies = [
        ("offering", "0002_benefit_credits_accountbenefitdiscount_accountbenefit"),
    ]

    operations = [
        migrations.RunPython(
            create_accounts_for_organizations,
            migrations.RunPython.noop,
        ),
    ]
