# Generated by Django 4.2.25 on 2025-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offering", "0003_create_accounts_for_organizations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountowner",
            name="permission_type",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("programmatic_contact", "Programmatic Contact"),
                    ("billing_contact", "Billing Contact"),
                ],
                max_length=30,
            ),
        ),
    ]
