# Generated by Django 5.2.12 on 2026-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offering", "0005_create_account_benefits_for_open_training_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountbenefit",
            name="registration_code",
            field=models.CharField(
                blank=True,
                help_text="Unique registration code used for account benefit identification.",
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Registration Code",
            ),
        ),
    ]
