# Generated by Django 5.2.12 on 2026-03-15 16:06

from uuid import uuid4

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def set_registration_code_to_fulfill_constraint(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    AccountBenefit = apps.get_model("offering", "AccountBenefit")

    # To satisfy the new constraint, we need to ensure that all AccountBenefits linked to a partnership have a null
    # registration code, and all AccountBenefits not linked to a partnership have a non-null registration code.
    for account_benefit in AccountBenefit.objects.filter(partnership__isnull=True, registration_code__isnull=True):
        account_benefit.registration_code = str(uuid4())
        account_benefit.save()

    for account_benefit in AccountBenefit.objects.filter(partnership__isnull=False, registration_code__isnull=False):
        account_benefit.registration_code = None
        account_benefit.save()


class Migration(migrations.Migration):
    dependencies = [
        ("fiscal", "0005_alter_partnership_tier"),
        ("offering", "0006_accountbenefit_registration_code"),
        ("workshops", "0292_alter_trainingrequest_member_code_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_registration_code_to_fulfill_constraint,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="accountbenefit",
            name="registration_code",
            field=models.CharField(
                blank=True,
                help_text="Unique registration code used for account benefit identification. "
                "Required if the account benefit is not linked to a partnership. If the account benefit is"
                " linked to a partnership, the registration code will be inherited from the partnership and cannot be"
                " set directly on the account benefit.",
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Registration Code",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountbenefit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("partnership__isnull", False), ("registration_code__isnull", True)),
                    models.Q(("partnership__isnull", True), ("registration_code__isnull", False)),
                    _connector="OR",
                ),
                name="check_partnership_registration_code",
                violation_error_message="Account Benefit, if linked to partnership, cannot have a registration code. "
                "If not linked to partnership, the registration code is required.",
            ),
        ),
    ]
