# Generated by Django 5.2.12 on 2026-03-22 17:13

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def set_discount_to_satisfy_constraint(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    AccountBenefit = apps.get_model("offering", "AccountBenefit")
    AccountBenefitDiscount = apps.get_model("offering", "AccountBenefitDiscount")
    default_discount, _ = AccountBenefitDiscount.objects.get_or_create(name="Other Discount")

    # To satisfy the new constraint, we need to ensure that all AccountBenefits linked to a partnership have a null
    # discount, and all AccountBenefits not linked to a partnership have a non-null discount.
    for account_benefit in AccountBenefit.objects.filter(partnership__isnull=True, discount__isnull=True):
        account_benefit.discount = default_discount
        account_benefit.save()

    for account_benefit in AccountBenefit.objects.filter(partnership__isnull=False, discount__isnull=False):
        account_benefit.discount = None
        account_benefit.save()


class Migration(migrations.Migration):
    dependencies = [
        ("fiscal", "0006_partnership_discount"),
        ("offering", "0007_alter_accountbenefit_registration_code_and_more"),
        ("workshops", "0292_alter_trainingrequest_member_code_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_discount_to_satisfy_constraint,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="accountbenefit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("partnership__isnull", False), ("discount__isnull", True)),
                    models.Q(("partnership__isnull", True), ("discount__isnull", False)),
                    _connector="OR",
                ),
                name="check_partnership_discount",
                violation_error_message="Account Benefit, if linked to partnership, cannot have a discount. "
                "If not linked to partnership, the discount is required.",
            ),
        ),
    ]
