# Generated by Django 5.2.14 on 2026-07-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0008_accountbenefit_check_partnership_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['name']},
        ),
    ]
