# Generated by Django 2.2.17 on 2021-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_squashed_0002_auto_20210314_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='Help Text'),
        ),
    ]
