# Generated by Django 2.2.17 on 2021-04-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_squashed_0002_auto_20210314_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='term_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='consents.TermOption'),
        ),
        migrations.AlterField(
            model_name='termoption',
            name='option_type',
            field=models.CharField(choices=[('agree', 'Agree'), ('decline', 'Decline')], max_length=40),
        ),
    ]
