# Generated by Django 2.2.17 on 2021-03-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='term_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='consents.TermOption'),
        ),
        migrations.AlterField(
            model_name='termoption',
            name='option_type',
            field=models.CharField(choices=[('agree', 'Agree'), ('decline', 'Decline')], max_length=40),
        ),
    ]
