# Generated by Django 2.2.17 on 2021-04-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0002_auto_20210401_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='Help Text'),
        ),
    ]
