# Generated by Django 3.2.18 on 2023-03-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0256_auto_20230220_2051'),
        ('consents', '0007_term_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequestConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consents.term')),
                ('term_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='consents.termoption')),
                ('training_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.trainingrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainingrequestconsent',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('training_request', 'term'), name='training_request__term__unique__when__archived_at__null'),
        ),
    ]
