# Generated by Django 2.2.24 on 2021-12-05 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0250_auto_20210807_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorRecruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('o', 'Open'), ('c', 'Closed')], default='o', max_length=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='workshops.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructorRecruitmentSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.CharField(choices=[('p', 'Pending'), ('d', 'Discarded'), ('a', 'Accepted')], default='p', max_length=1)),
                ('interest', models.CharField(choices=[('session', 'Whole session'), ('part', 'Part of session'), ('support', 'Supporting instructor')], max_length=10)),
                ('user_notes', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.InstructorRecruitment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
