# Generated by Django 3.2.13 on 2022-05-26 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20220220_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrecruitmentsignup',
            name='rq_jobs',
            field=models.ManyToManyField(blank=True, help_text='This should be filled out by AMY itself.', to='autoemails.RQJob', verbose_name='Related Redis Queue jobs'),
        ),
        migrations.AlterField(
            model_name='instructorrecruitmentsignup',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='recruitment.instructorrecruitment'),
        ),
    ]
