# Generated by Django 3.2.14 on 2022-09-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0254_alter_trainingrequest_github"),
        ("communityroles", "0003_communityroleconfig_autoassign_when_award_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityrole",
            name="award",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workshops.award",
                verbose_name="Associated Award",
            ),
        ),
        migrations.AlterField(
            model_name="communityrole",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="communityroles.communityroleconfig",
                verbose_name="Role Name",
            ),
        ),
        migrations.AlterField(
            model_name="communityrole",
            name="end",
            field=models.DateField(blank=True, null=True, verbose_name="Role End Date"),
        ),
        migrations.AlterField(
            model_name="communityrole",
            name="inactivation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="communityroles.communityroleinactivation",
                verbose_name="Reason for inactivation",
            ),
        ),
        migrations.AlterField(
            model_name="communityrole",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workshops.membership",
                verbose_name="Associated Membership",
            ),
        ),
        migrations.AlterField(
            model_name="communityrole",
            name="start",
            field=models.DateField(blank=True, null=True, verbose_name="Role Start Date"),
        ),
    ]
