# Generated by Django 3.2.14 on 2022-09-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communityroles", "0004_communityrole_field_verbose_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityrole",
            name="start",
            field=models.DateField(null=True, verbose_name="Role Start Date"),
        ),
    ]
