# Generated by Django 5.2.9 on 2026-01-24 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communityroles", "0005_alter_communityrole_start"),
        ("fiscal", "0004_alter_partnership_registration_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityrole",
            name="partnership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fiscal.partnership",
                verbose_name="Associated Partnership",
            ),
        ),
        migrations.AddField(
            model_name="communityroleconfig",
            name="link_to_partnership",
            field=models.BooleanField(default=False, verbose_name="Should link to a Membership?"),
        ),
    ]
