# Generated by Django 5.2.9 on 2026-05-12 00:00

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def copy_partnership_fk_to_m2m(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    CommunityRole = apps.get_model("communityroles", "CommunityRole")
    for role in CommunityRole.objects.exclude(partnership__isnull=True).iterator():
        role.partnership_new.add(role.partnership_id)


def copy_partnership_m2m_to_fk(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    CommunityRole = apps.get_model("communityroles", "CommunityRole")
    for role in CommunityRole.objects.iterator():
        first_partnership = role.partnership_new.order_by("pk").first()
        if first_partnership is not None:
            role.partnership = first_partnership
            role.save(update_fields=["partnership"])


class Migration(migrations.Migration):
    dependencies = [
        ("communityroles", "0006_communityrole_partnership_and_more"),
        ("fiscal", "0007_add_is_custom_to_partnershiptier"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityrole",
            name="partnership_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="fiscal.partnership",
                verbose_name="Associated Partnership",
            ),
        ),
        migrations.RunPython(
            copy_partnership_fk_to_m2m,
            copy_partnership_m2m_to_fk,
        ),
        migrations.RemoveField(
            model_name="communityrole",
            name="partnership",
        ),
        migrations.RenameField(
            model_name="communityrole",
            old_name="partnership_new",
            new_name="partnerships",
        ),
        migrations.AlterField(
            model_name="communityrole",
            name="partnerships",
            field=models.ManyToManyField(
                blank=True,
                to="fiscal.partnership",
                verbose_name="Associated Partnership",
            ),
        ),
    ]
