# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0075_invoicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invoice_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('invoiced', 'Invoiced'), ('not-invoiced', 'Not invoiced'), ('na-historic', 'Not applicable for historical reasons'), ('na-member', 'Not applicable because of membership'), ('na-self-org', 'Not applicable because self-organized'), ('na-waiver', 'Not applicable because waiver granted'), ('na-other', 'Not applicable because other arrangements made')], default='unknown', max_length=40, verbose_name='Invoice status'),
        ),
    ]
