# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0076_auto_20160208_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerequest',
            name='paid_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Date invoice was paid'),
        ),
        migrations.AddField(
            model_name='invoicerequest',
            name='sent_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Date invoice was sent out'),
        ),
        migrations.AlterField(
            model_name='invoicerequest',
            name='full_address',
            field=models.TextField(help_text='e.g. Dr. Jane Smith; University of Florida Ecology Department; 123 University Way; Gainesville, FL 32844', verbose_name='Full address to invoice'),
        ),
        migrations.AlterField(
            model_name='invoicerequest',
            name='status',
            field=models.CharField(choices=[('not-invoiced', 'Not invoiced'), ('sent', 'Sent out'), ('paid', 'Paid')], default='not-invoiced', max_length=40, verbose_name='Invoice status'),
        ),
    ]
