# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0077_auto_20160208_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerequest',
            name='contact_email',
            field=models.EmailField(max_length=100, verbose_name='Organization contact email'),
        ),
    ]
