# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0078_auto_20160212_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(verbose_name="Link to the workshop's website")),
                ('contact_name', models.CharField(max_length=100, verbose_name='Your name')),
                ('contact_email', models.EmailField(help_text='We may need to contact you regarding workshop details.', max_length=254, verbose_name='Your email')),
                ('self_organized', models.BooleanField(default=False, verbose_name='Was the workshop self-organized?')),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
