# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0085_merge'),
        ('workshops', '0082_certificate'),
    ]

    operations = [
    ]
