# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0086_auto_20160416_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Event',
            old_name='repository_tags',
            new_name='repository_metadata'
        ),
    ]
