# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-17 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0086_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='download_ready',
            field=models.BooleanField(default=False),
        ),
    ]
