# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('workshops', '0087_renaming_column_repository_tags'), ('workshops', '0088_alter_help_text_of_repository_metadata_field'), ('workshops', '0089_renaming_column_tag_changes_detected'), ('workshops', '0090_alter_help_text_of_metadata_all_changes'), ('workshops', '0091_rename_column_tags_changed'), ('workshops', '0092_alter_help_text_of_metadata_changed')]

    dependencies = [
        ('workshops', '0086_auto_20160416_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Event',
            old_name='repository_tags',
            new_name='repository_metadata',
        ),
        migrations.AlterField(
            model_name='event',
            name='repository_metadata',
            field=models.TextField(blank=True, default='', help_text="JSON-serialized metadata from event's website"),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tag_changes_detected',
            new_name='metadata_all_changes',
        ),
        migrations.AlterField(
            model_name='event',
            name='metadata_all_changes',
            field=models.TextField(blank=True, default='', help_text='List of detected metadata changes'),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tags_changed',
            new_name='metadata_changed',
        ),
        migrations.AlterField(
            model_name='event',
            name='metadata_changed',
            field=models.BooleanField(default=False, help_text='Indicate if metadata changed since last check'),
        ),
    ]
