# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0087_renaming_column_repository_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repository_metadata',
            field=models.TextField(blank=True, default='', help_text="JSON-serialized metadata from event's website"),
        ),
    ]
