# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0088_alter_help_text_of_repository_metadata_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tag_changes_detected',
            new_name='metadata_all_changes',
        ),
    ]
