# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0090_alter_help_text_of_metadata_all_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tags_changed',
            new_name='metadata_changed',
        ),
    ]
