# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0091_rename_column_tags_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='metadata_changed',
            field=models.BooleanField(default=False, help_text='Indicate if metadata changed since last check'),
        ),
    ]
