# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0094_modify_role_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personal', models.CharField(max_length=100, verbose_name='Personal name')),
                ('family', models.CharField(max_length=100, verbose_name='Family name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('occupation', models.CharField(blank=True, choices=[('undisclosed', 'Prefer not to say'), ('undergrad', 'Undergraduate student'), ('grad', 'Graduate student'), ('postdoc', 'Post-doctoral researcher'), ('faculty', 'Faculty'), ('research', 'Research staff (including research programmer)'), ('support', 'Support staff (including technical support)'), ('librarian', 'Librarian/archivist'), ('commerce', 'Commercial software developer '), ('', 'Other (enter below)')], default='undisclosed', help_text='Please choose the one that best describes you.', max_length=40, verbose_name='What is your current occupation/career stage?')),
                ('occupation_other', models.CharField(blank=True, default='', max_length=100, verbose_name='Other occupation/career stage')),
                ('affiliation', models.CharField(max_length=100, verbose_name='Institutional Affiliation')),
                ('location', models.CharField(help_text='please give city, province or state', max_length=100, verbose_name='Location')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('domains_other', models.CharField(blank=True, default='', max_length=255, verbose_name='Other areas of expertise')),
                ('gender', models.CharField(choices=[('U', 'Prefer not to say'), ('F', 'Female'), ('M', 'Male'), ('O', 'Other (enter below)')], default='U', max_length=1)),
                ('gender_other', models.CharField(blank=True, default='', max_length=100, verbose_name=' ')),
                ('previous_training', models.CharField(choices=[('none', 'None'), ('hours', 'A few hours'), ('days', 'A few days'), ('full', 'A full degree'), ('other', 'Other (enter below)')], default='none', max_length=40, verbose_name='Previous training in teaching')),
                ('previous_training_other', models.CharField(blank=True, default='', max_length=100, verbose_name=' ')),
                ('previous_experience', models.CharField(choices=[('none', 'None'), ('hours', 'Have taught for a few hours'), ('courses', 'Have taught entire courses'), ('other', 'Other (enter below)')], default='none', max_length=40, verbose_name='Previous experience in teaching')),
                ('previous_experience_other', models.CharField(blank=True, default='', max_length=100, verbose_name=' ')),
                ('programming_language_usage_frequency', models.CharField(choices=[('all-time', 'Every waking moment'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('not-much', 'Not much')], default='all-time', max_length=40, verbose_name='How frequently do you use Python, R or Matlab?')),
                ('reason', models.TextField(verbose_name='Why do you want to attend this training course?')),
                ('teaching_frequency_expectation', models.CharField(choices=[('not-at-all', 'Not at all'), ('yearly', 'Once a year'), ('monthly', 'Several times a year'), ('often', 'Primary occupation'), ('other', 'Other (enter below)')], default='not-at-all', max_length=40, verbose_name='How often would you expect to teach classes on Softwareor Data Carpentry Workshops after this training?')),
                ('teaching_frequency_expectation_other', models.CharField(blank=True, default='', max_length=100, verbose_name=' ')),
                ('max_travelling_frequency', models.CharField(choices=[('not-at-all', 'Not at all'), ('yearly', 'Once a year'), ('often', 'Several times a year'), ('other', 'Other (enter below)')], default='not-at-all', max_length=40, verbose_name='How frequently would you be able to travel to teach such classes?')),
                ('max_travelling_frequency_other', models.CharField(blank=True, default='', max_length=100, verbose_name=' ')),
                ('additional_skills', models.TextField(blank=True, default='', verbose_name='Do you have any additional relevant skills or interests that we should know about?')),
                ('domains', models.ManyToManyField(blank=True, help_text='Please check all that apply.', to='workshops.KnowledgeDomain', verbose_name='Areas of expertise')),
                ('previous_involvement', models.ManyToManyField(blank=True, help_text='Please check all that apply.', to='workshops.Role', verbose_name='Previous involvement with Software Carpentry or Data Carpentry')),
            ],
        ),
    ]
