# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0096_change_help_text_in_training_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('role__name', 'event')},
        ),
    ]
