# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0097_add_admins_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='affiliation',
            field=models.CharField(blank=True, default='',
                                   help_text='What university, company, lab, or other organization are you affiliated with (if any)?',
                                   max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT,
                                    to='workshops.Airport', verbose_name='Nearest major airport'),
        ),
        migrations.AlterField(
            model_name='person',
            name='domains',
            field=models.ManyToManyField(blank=True, help_text='Please check all that apply.',
                                         to='workshops.KnowledgeDomain', verbose_name='Areas of expertise'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.CharField(max_length=100, null=False, verbose_name='Family (last) name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='github',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='GitHub username'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lessons',
            field=models.ManyToManyField(blank=True, help_text='Please check all that apply.',
                                         through='workshops.Qualification', to='workshops.Lesson',
                                         verbose_name='Topic and lessons you\'re comfortable teaching'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personal',
            field=models.CharField(max_length=100, null=False, verbose_name='Personal (first) name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Twitter username'),
        ),
        migrations.AlterField(
            model_name='person',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Personal website'),
        ),
    ]
