# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0099_auto_20160609_0106'),
        ('workshops', '0097_auto_20160618_1132'),
    ]

    operations = [
    ]
