# Generated by Django 1.9.6 on 2016-06-20 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0098_modify_person_model'),
        ('workshops', '0088_auto_20160530_1029'),
        ('workshops', '0101_merge'),
    ]

    operations = [
    ]
