# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0098_modify_person_model'),
        ('workshops', '0101_merge'),
    ]

    operations = [
    ]
