# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0102_task_title'),
        ('workshops', '0102_merge'),
        ('workshops', '0102_profileupdaterequest_languages'),
    ]

    operations = [
    ]
