# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0105_auto_20160630_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='Use <code>YYYY-MM-DD-location</code> format, where <code>location</code> is either an organization, or city, or both. If the specific date is unknown, use <code>xx</code> instead, for example: <code>2016-12-xx-Krakow</code> means that the event is supposed to run sometime in December 2016 in Kraków. Use only latin characters.', max_length=100, unique=True),
        ),
    ]
