# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0106_auto_20160701_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='What else do you want us to know?', verbose_name='Anything else?'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='group_name',
            field=models.CharField(blank=True, default='', help_text="If you are part of a group that is applying for an instructor training together, please enter the name of your group here and on every group member's application.", max_length=100, verbose_name='Group name'),
        ),
    ]
