# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0108_training_request_form_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 1992.33', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sponsorship amount')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.Event')),
                ('organization', models.ForeignKey(help_text='Organization sponsoring the event', on_delete=django.db.models.deletion.CASCADE, to='workshops.Host')),
            ],
        ),
    ]
