# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0110_event_sponsors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Host',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='host',
            new_name='organization',
        ),
    ]
