# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-18 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0111_migrate_host_to_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
