# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models


def add_option_to_data_analysis_level(apps, schema_editor):
    dal = apps.get_model('workshops', 'DataAnalysisLevel')
    dal.objects.get_or_create(name='Don\'t know yet')


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0116_auto_20160902_1413'),
    ]

    operations = [
        migrations.RunPython(add_option_to_data_analysis_level),
        migrations.AlterField(
            model_name='dcselforganizedeventrequest',
            name='topics',
            field=models.ManyToManyField(help_text='A Data Carpentry workshop must include a Data Carpentry lesson on data organization and three other modules in the same domain from the Data Carpentry curriculum (see <a href="http://www.datacarpentry.org/workshops/">http://www.datacarpentry.org/workshops/</a>). If you do want to include materials not in our curriculum, please note that below and we\'ll get in touch.', to='workshops.DCWorkshopTopic', verbose_name='Topics to be taught'),
        ),
    ]
