# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0118_auto_20160922_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invoice_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('invoiced', 'Invoice requested'), ('not-invoiced', 'Invoice not requested'), ('na-historic', 'Not applicable for historical reasons'), ('na-member', 'Not applicable because of membership'), ('na-self-org', 'Not applicable because self-organized'), ('na-waiver', 'Not applicable because waiver granted'), ('na-other', 'Not applicable because other arrangements made'), ('paid', 'Paid')], default='not-invoiced', max_length=40, verbose_name='Invoice status'),
        ),
        migrations.AlterField(
            model_name='invoicerequest',
            name='status',
            field=models.CharField(choices=[('not-invoiced', 'Invoice not requested'), ('sent', 'Sent out'), ('paid', 'Paid')], default='not-invoiced', max_length=40, verbose_name='Invoice status'),
        ),
    ]
