# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0119_auto_20161023_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdaterequest',
            name='middle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='middle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle name'),
        ),
    ]
