# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0119_auto_20161023_1413'),
        ('workshops', '0119_auto_20160929_1131'),
    ]

    operations = [
    ]
