# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-01 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0121_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='contribution_type',
            field=models.CharField(choices=[('financial', 'Financial'), ('person-days', 'Person-days'), ('other', 'Other')], max_length=40),
        ),
    ]
