# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0122_auto_20161101_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='self_organized_workshops_per_year',
            field=models.PositiveIntegerField(blank=True, help_text='Expected number of self-organized workshops per year', null=True),
        ),
    ]
