# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 16:18
from __future__ import unicode_literals

from django.db import migrations
import workshops.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0124_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='github',
            field=workshops.models.NullableGitHubUsernameField(blank=True, default='', max_length=40, null=True, unique=True, verbose_name='GitHub username'),
        ),
        migrations.AlterField(
            model_name='profileupdaterequest',
            name='github',
            field=workshops.models.NullableGitHubUsernameField(blank=True, default='', help_text='Please provide your username, not a numeric user ID.', max_length=40, null=True, verbose_name='GitHub username'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='github',
            field=workshops.models.NullableGitHubUsernameField(blank=True, default='', max_length=40, null=True, verbose_name='GitHub username'),
        ),
    ]
