# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0126_auto_20170325_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Family (last) name'),
        ),
    ]
