# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models


PREVIOUS_NAME_MAX_LENGTH = 40


def fix_truncated_language_names(apps, schema_editor):
    """Some languages names were truncated in 0097_auto_20160519_0739 migration.

    See https://github.com/swcarpentry/amy/issues/1165 for more info."""

    Language = apps.get_model('workshops', 'Language')
    languages_to_fix = [
        'Church Slavic Church Slavonic Old Bulgarian Old Church Slavonic Old Slavonic',
        'Interlingua (International Auxiliary Language Association)',
    ]
    for language_name in languages_to_fix:
        truncated = language_name[:PREVIOUS_NAME_MAX_LENGTH]
        try:
            lang = Language.objects.get(name=truncated)
        except Language.DoesNotExist:
            pass
        else:
            lang.name = language_name
            lang.save()


class Migration(migrations.Migration):
    dependencies = [
        ('workshops', '0126_auto_20170325_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Description of this language tag in English', max_length=100),
        ),
        migrations.RunPython(fix_truncated_language_names),
    ]
