# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-09 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0127_make_family_name_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('iata',)},
        ),
    ]
