# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-10 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0127_make_family_name_optional'),
        ('workshops', '0127_fix_language_names'),
    ]

    operations = [
    ]
