# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-02-11 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0130_trainingrequest_new_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrequest',
            name='additional_skills',
        ),
        migrations.RemoveField(
            model_name='trainingrequest',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='trainingrequest',
            name='gender_other',
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='previous_training',
            field=models.CharField(choices=[('none', 'None'), ('hours', 'A few hours'), ('workshop', 'A workshop'), ('course', 'A certification or short course'), ('full', 'A full degree'), ('other', 'Other (enter below)')], default='none', help_text=None, max_length=40, verbose_name='Previous formal training as a teacher or instructor'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='teaching_frequency_expectation',
            field=models.CharField(choices=[('not-at-all', 'Not at all'), ('yearly', 'Once a year'), ('monthly', 'Several times a year'), ('other', 'Other (enter below)')], default='not-at-all', help_text=None, max_length=40, verbose_name='How often would you expect to teach Carpentry Workshops after this training?'),
        ),
    ]
