# Generated by Django 2.0.5 on 2018-05-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0136_auto_20180524_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='data_privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html", target="_blank">the data privacy policy</a> of The Carpentries.'),
        ),
        migrations.AddField(
            model_name='profileupdaterequest',
            name='data_privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html", target="_blank">the data privacy policy</a> of The Carpentries.'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='data_privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html", target="_blank">the data privacy policy</a> of The Carpentries.'),
        ),
    ]
