# Generated by Django 2.0.5 on 2018-05-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0137_auto_20180524_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='publish_profile',
            field=models.BooleanField(default=False, help_text='Allow to post your name and any public profile you list (website, Twitter) on our instructors website. Emails will not be posted.', verbose_name='Consent to making profile public'),
        ),
        migrations.AlterField(
            model_name='profileupdaterequest',
            name='publish_profile',
            field=models.BooleanField(default=False, help_text='Allow to post your name and any public profile you list (website, Twitter) on our instructors website. Emails will not be posted.', verbose_name='Consent to making profile public'),
        ),
    ]
