# Generated by Django 2.0.5 on 2018-07-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0141_auto_20180531_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='code_of_conduct_agreement',
            field=models.BooleanField(default=False, verbose_name='I agree to abide by The Carpentries\' <a target="_blank"href="https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html">Code of Conduct</a>.'),
        ),
    ]
