# Generated by Django 2.0.7 on 2018-08-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0146_uppercase_url_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='self_organized_workshops_per_year',
            new_name='self_organized_workshops_per_agreement',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='workshops_without_admin_fee_per_year',
            new_name='workshops_without_admin_fee_per_agreement',
        ),
        migrations.AlterField(
            model_name='membership',
            name='self_organized_workshops_per_agreement',
            field=models.PositiveIntegerField(blank=True, help_text='Expected number of self-organized workshops per agreement duration', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='workshops_without_admin_fee_per_agreement',
            field=models.PositiveIntegerField(blank=True, help_text='Acceptable number of workshops without admin fee per agreement duration', null=True),
        ),
    ]
