# Generated by Django 2.1 on 2018-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0154_auto_20180913_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrequest',
            name='active',
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='score_auto',
            field=models.PositiveIntegerField(default=0, help_text='Filled out by AMY.', verbose_name='Application automatic score'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='score_manual',
            field=models.IntegerField(default=0, help_text='Filled out by admin.', verbose_name='Application manual score (can be negative)'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='score_notes',
            field=models.TextField(blank=True, help_text='Explanation of manual score, if necessary.', verbose_name='Notes regarding manual score'),
        ),
    ]
