# Generated by Django 2.1.2 on 2018-10-27 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0157_auto_20181006_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.CharField(default='', help_text="Use computer-friendly text here, e.g. 'dc-ecology-r'.", max_length=40, unique=True, verbose_name='Curriculum ID')),
                ('name', models.CharField(default='', help_text="Use user-friendly language, e.g. 'Data Carpentry (Ecology with R)'.", max_length=200, unique=True, verbose_name='Curriculum name')),
                ('unknown', models.BooleanField(blank=True, default=False, help_text="Mark this curriculum record as 'I don't know yet', or 'Unknown', or 'Not sure yet'. There can be only one such record in the database.", verbose_name='Unknown entry')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
            },
        ),
        migrations.CreateModel(
            name='WorkshopRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('data_privacy_agreement', models.BooleanField(default=False, verbose_name='I have read and agree to <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html", target="_blank">the data privacy policy</a> of The Carpentries.')),
                ('code_of_conduct_agreement', models.BooleanField(default=False, verbose_name='I agree to abide by The Carpentries\' <a target="_blank"href="https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html">Code of Conduct</a>.')),
                ('host_responsibilities', models.BooleanField(default=False, verbose_name='I understand <a href="https://docs.carpentries.org/topic_folders/hosts_instructors/index.html">the responsibilities of the workshop host</a>, including recruiting local helpers to support the workshop (1 helper for every 8-10 learners).')),
                ('state', models.CharField(choices=[('p', 'Pending'), ('d', 'Discarded'), ('a', 'Accepted')], default='p', max_length=1)),
                ('personal', models.CharField(max_length=255, verbose_name='Personal (given) name')),
                ('family', models.CharField(max_length=255, verbose_name='Family name (surname)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('institution_name', models.CharField(blank=True, default='', max_length=255, verbose_name="Name of institution you're affiliated with")),
                ('institution_department', models.CharField(blank=True, default='', max_length=255, verbose_name='Department/school affiliation (if applicable)')),
                ('location', models.CharField(default='', help_text='City, province/state.', max_length=255, verbose_name='Location')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('part_of_conference', models.BooleanField(help_text='We can manage registration and other coordination for our workshop, but not other conference activities.', verbose_name='Is this workshop part of conference or larger event?')),
                ('conference_details', models.CharField(blank=True, default='', help_text='Name, description (if applicable).', max_length=255, verbose_name='Conference details')),
                ('preferred_dates', models.CharField(default='', help_text='Because we need to coordinate with instructors, a minimum of 2-3 months lead time is required for workshop planning.', max_length=255, verbose_name='Preferred dates or date range')),
                ('number_attendees', models.CharField(choices=[('10-40', '10-40 (one room, two instructors)'), ('40-80', '40-80 (two rooms, four instructors)'), ('80-120', '80-120 (three rooms, six instructors)')], default='10-40', help_text="This number doesn't need to be precise, but will help us decide how many instructors your workshop will need. Each workshop must have at least two instructors.", max_length=15, verbose_name='Number of attendees')),
                ('domains_other', models.CharField(blank=True, default='', max_length=255, verbose_name='Other domains')),
                ('audience_description', models.TextField(verbose_name='Please describe your anticipated audience, including their experience, background, and goals')),
                ('organization_type', models.CharField(choices=[('self', 'Self-organized'), ('central', 'Centrally-organized')], default=None, max_length=15, verbose_name='Will this be a self-organized or centrally-organized workshop?')),
                ('self_organized_github', models.CharField(blank=True, help_text='Please provide URL.', max_length=255, verbose_name='Link to workshop GitHub page')),
                ('centrally_organized_fee', models.CharField(blank=True, choices=[('', 'Not applicable.'), ('nonprofit', 'I am with a government site, university, or other nonprofit. I understand the workshop fee of US$2500, and agree to follow through on The Carpentries invoicing process.'), ('forprofit', 'I am with a corporate or for-profit site. I understand The Carpentries staff will contact me about workshop fees. I will follow through on The Carpentries invoicing process for the agreed upon fee.'), ('member', 'I am with a Member Organisation so the workshop fee does not apply (Instructor travel costs will still apply).'), ('waiver', 'I am requesting a waiver of the workshop fee (Instructor travel costs will still apply).')], default='', max_length=20, verbose_name='Which of the following applies to your payment for the administrative fee?')),
                ('waiver_circumstances', models.TextField(blank=True, help_text='Required only if you request a waiver.', verbose_name='Please explain the circumstances for your waiver request')),
                ('travel_expences_agreement', models.BooleanField(default=False, verbose_name='Regardless of the fee due to The Carpentries, I understand I am also responsible for travel costs for the Instructors which can include airfare, ground travel, hotel, and meals/incidentals. I understand local Instructors will be prioritized but not guaranteed. Instructor travel costs are managed directly between the host site and the Instructors, not through The Carpentries. I will share detailed information regarding policies and procedures for travel arrangements with instructors. All reimbursements will be completed within 60 days of the workshop.')),
                ('travel_expences_management', models.CharField(choices=[('booked', 'Hotel and airfare will be booked by site; ground travel and meals/incidentals will be reimbursed within 60 days.'), ('reimbursed', 'All expenses will be booked by instructors and reimbursed within 60 days.'), ('', 'Other:')], max_length=20, verbose_name='How will you manage travel expenses for Carpentries Instructors?')),
                ('travel_expences_management_other', models.CharField(blank=True, default='', max_length=255, verbose_name='Other travel expences management')),
                ('comment', models.TextField(blank=True, verbose_name='Is there anything else you would like to share with us?')),
                ('academic_levels', models.ManyToManyField(help_text="If you know the academic level(s) of your attendees, indicate them here.'", to='workshops.AcademicLevel', verbose_name="Attendees' academic level / career stage")),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('computing_levels', models.ManyToManyField(help_text="Indicate the attendees' level of computing experience, if known. We will ask attendees to fill in a skills survey before the workshop, so this answer can be an approximation.", to='workshops.ComputingExperienceLevel', verbose_name="Attendees' level of computing experience")),
                ('domains', models.ManyToManyField(help_text="The attendees' academic field(s) of study, if known.", to='workshops.KnowledgeDomain', verbose_name='Domains or topic of interest for target audience')),
                ('institution', models.ForeignKey(blank=True, help_text="If your institution isn't on the list, enter its name in the field below.", null=True, on_delete=django.db.models.deletion.PROTECT, to='workshops.Organization', verbose_name='Institutional affiliation')),
                ('language', models.ForeignKey(help_text='Our workshops are offered primarily in English, with a few of our lessons available in Spanish. While materials are mainly in English, we know it can be valuable to have an instructor who speaks the native language of the learners. We will attempt to locate Instructors speaking a particular language, but cannot guarantee the availability of non-English speaking Instructors.', on_delete=django.db.models.deletion.PROTECT, to='workshops.Language', verbose_name='Language')),
                ('requested_workshop_types', models.ManyToManyField(help_text="If your learners are new to programming and primarily interested in working with data, Data Carpentry is likely the best choice. If your learners are interested in learning more about programming, including version control and automation, Software Carpentry is likely the best match. Please visit the <a href='https://software-carpentry.org/lessons/'>Software Carpentry lessons page</a> or the <a href='http://www.datacarpentry.org/lessons/'>Data Carpentry lessons page</a> for more information about any of our lessons. If you’re not sure and would like to discuss with us, please select the 'Not sure' option below.", limit_choices_to={'active': True}, to='workshops.Curriculum', verbose_name='Which Carpentry workshop are you requesting?')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
