# Generated by Django 2.1.2 on 2018-10-28 08:45

from django.db import migrations, models
from django.db.models import Q


def add_curricula(apps, schema_editor):
    """Populate database with Curriculum objects."""
    Curriculum = apps.get_model('workshops', 'Curriculum')
    data = {
        'swc-python': dict(
            name='Software Carpentry (shell, git, Python)',
            active=True,
            unknown=False,
        ),
        'swc-r': dict(
            name='Software Carpentry (shell, git, R)',
            active=True,
            unknown=False,
        ),
        'swc-es-python': dict(
            name='Software Carpentry in Spanish (shell, git, Python)',
            active=True,
            unknown=False,
        ),
        'swc-es-r': dict(
            name='Software Carpentry in Spanish (shell, git, R)',
            active=True,
            unknown=False,
        ),
        'swc-other': dict(
            name='Software Carpentry (other)',
            active=True,
            unknown=False,
        ),
        'dc-ecology-python': dict(
            name='Data Carpentry (Ecology with Python)',
            active=True,
            unknown=False,
        ),
        'dc-ecology-r': dict(
            name='Data Carpentry (Ecology with R)',
            active=True,
            unknown=False,
        ),
        'dc-genomics': dict(
            name='Data Carpentry (Genomics)',
            active=True,
            unknown=False,
        ),
        'dc-geospatial': dict(
            name='Data Carpentry (Geospatial)',
            active=True,
            unknown=False,
        ),
        'dc-socsci-python': dict(
            name='Data Carpentry (Social Sciences with Python)',
            active=True,
            unknown=False,
        ),
        'dc-socsci-r': dict(
            name='Data Carpentry (Social Sciences with R)',
            active=True,
            unknown=False,
        ),
        'dc-other': dict(
            name='Data Carpentry (other)',
            active=True,
            unknown=False,
        ),
        'lc': dict(
            name='Library Carpentry',
            active=True,
            unknown=False,
        ),
        'unknown': dict(
            name="Don't know yet",
            active=True,
            unknown=True,
        ),
    }
    for slug, defaults in data.items():
        Curriculum.objects.get_or_create(
            slug=slug,
            defaults=defaults,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0159_auto_20181027_1237'),
    ]

    operations = [
        migrations.RunPython(add_curricula)
    ]
