# Generated by Django 2.1.2 on 2018-10-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0160_curriculum_objects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['slug'], 'verbose_name': 'Curriculum', 'verbose_name_plural': 'Curricula'},
        ),
        migrations.AddField(
            model_name='event',
            name='curricula',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True, 'unknown': False}, to='workshops.Curriculum', verbose_name='Curricula taught at the workshop'),
        ),
    ]
