from django.conf.urls import url
from workshops import views

urlpatterns = [
    url(r'^$', views.dispatch, name='dispatch'),
    url(r'^admin-dashboard/$', views.admin_dashboard, name='admin-dashboard'),
    url(r'^trainee-dashboard/$', views.trainee_dashboard, name='trainee-dashboard'),

    url(r'^log/$', views.changes_log, name='changes_log'),

    url(r'^hosts/?$', views.all_hosts, name='all_hosts'),
    url(r'^host/(?P<host_domain>[\w\.-]+)/?$', views.host_details, name='host_details'),
    url(r'^host/(?P<host_domain>[\w\.-]+)/edit$', views.HostUpdate.as_view(), name='host_edit'),
    url(r'^host/(?P<host_domain>[\w\.-]+)/delete$', views.host_delete, name='host_delete'),
    url(r'^hosts/add/$', views.HostCreate.as_view(), name='host_add'),

    url(r'membership/(?P<host_domain>[\w\.-]+)/add', views.membership_create, name='membership_add'),
    url(r'membership/(?P<membership_id>\d+)/edit', views.MembershipUpdate.as_view(), name='membership_edit'),
    url(r'membership/(?P<membership_id>\d+)/delete', views.membership_delete, name='membership_delete'),

    url(r'^airports/?$', views.all_airports, name='all_airports'),
    url(r'^airport/(?P<airport_iata>\w+)/?$', views.airport_details, name='airport_details'),
    url(r'^airport/(?P<airport_iata>\w+)/edit$', views.AirportUpdate.as_view(), name='airport_edit'),
    url(r'^airport/(?P<airport_iata>\w+)/delete$', views.airport_delete, name='airport_delete'),
    url(r'^airports/add/$', views.AirportCreate.as_view(), name='airport_add'),

    url(r'^persons/?$', views.all_persons, name='all_persons'),
    url(r'^person/(?P<person_id>[\w\.-]+)/?$', views.person_details, name='person_details'),
    url(r'^person/(?P<person_id>[\w\.-]+)/edit$', views.person_edit, name='person_edit'),
    url(r'^person/(?P<person_id>[\w\.-]+)/delete$', views.person_delete, name='person_delete'),
    url(r'^person/(?P<person_id>[\w\.-]+)/permissions$', views.PersonPermissions.as_view(), name='person_permissions'),
    url(r'^person/(?P<person_id>[\w\.-]+)/password$', views.person_password, name='person_password'),
    url(r'^persons/add/$', views.PersonCreate.as_view(), name='person_add'),
    url(r'^persons/bulkadd/$',views.person_bulk_add, name='person_bulk_add'),
    url(r'^persons/bulkadd/template',views.person_bulk_add_template, name='person_bulk_add_template'),
    url(r'^persons/bulkadd/confirm$',views.person_bulk_add_confirmation, name='person_bulk_add_confirmation'),
    url(r'^persons/merge/$', views.persons_merge, name='persons_merge'),

    url(r'^events/?$', views.all_events, name='all_events'),
    url(r'^event/(?P<event_ident>[\w-]+)/?$', views.event_details, name='event_details'),
    url(r'^event/(?P<event_ident>[\w-]+)/assign$', views.event_assign, name='event_assign'),
    url(r'^event/(?P<event_ident>[\w-]+)/assign/(?P<person_id>[\w\.-]+)$', views.event_assign, name='event_assign'),
    url(r'^event/(?P<event_ident>[\w-]+)/edit$', views.event_edit, name='event_edit'),
    url(r'^event/(?P<event_ident>[\w-]+)/delete$', views.event_delete, name='event_delete'),
    url(r'^events/add/$', views.EventCreate.as_view(), name='event_add'),
    url(r'^event/(?P<event_ident>[\w-]+)/validate/?$', views.validate_event, name='validate_event'),
    url(r'^events/metadata_changed/?$', views.events_metadata_changed, name='events_metadata_changed'),
    url(r'^event/(?P<event_ident>[\w-]+)/review_metadata_changes/?$', views.event_review_metadata_changes, name='event_review_metadata_changes'),
    url(r'^event/(?P<event_ident>[\w-]+)/review_metadata_changes/accept/?$', views.event_accept_metadata_changes, name='event_accept_metadata_changes'),
    url(r'^event/(?P<event_ident>[\w-]+)/review_metadata_changes/dismiss/?$', views.event_dismiss_metadata_changes, name='event_dismiss_metadata_changes'),
    url(r'^events/import/?$', views.event_import, name='event_import'),
    url(r'^events/merge/?$', views.events_merge, name='events_merge'),

    url(r'^event/(?P<event_ident>[\w-]+)/invoice$', views.event_invoice, name='event_invoice'),
    url(r'^invoices/?$', views.AllInvoiceRequests.as_view(), name='all_invoicerequests'),
    url(r'^invoice/(?P<request_id>\d+)/?$', views.InvoiceRequestDetails.as_view(), name='invoicerequest_details'),
    url(r'^invoice/(?P<request_id>\d+)/edit$', views.InvoiceRequestUpdate.as_view(), name='invoicerequest_edit'),

    url(r'^tasks/?$', views.all_tasks, name='all_tasks'),
    url(r'^task/(?P<task_id>\d+)/?$', views.task_details, name='task_details'),
    url(r'^task/(?P<task_id>\d+)/edit$', views.TaskUpdate.as_view(), name='task_edit'),
    url(r'^task/(?P<task_id>\d+)/delete$', views.task_delete, name='task_delete'),
    url(r'^event/(?P<event_ident>[\w-]+)/task/(?P<task_id>\d+)/delete$', views.task_delete, name='task_delete'),
    url(r'^tasks/add/$', views.TaskCreate.as_view(), name='task_add'),

    url(r'^award/(?P<award_id>\d+)/delete$', views.award_delete, name='award_delete'),
    url(r'^person/(?P<person_id>[\w\.-]+)/award/(?P<award_id>\d+)/delete$', views.award_delete, name='award_delete'),

    url(r'^badges/?$', views.all_badges, name='all_badges'),
    url(r'^badge/(?P<badge_name>[\w\.=-]+)/?$', views.badge_details, name='badge_details'),
    url(r'^badge/(?P<badge_name>[\w\.=-]+)/award/?$', views.badge_award, name='badge_award'),

    url(r'^trainings/?$', views.all_trainings, name='all_trainings'),

    url(r'^workshop_staff/?$', views.workshop_staff, name='workshop_staff'),

    url(r'^search/?$', views.search, name='search'),

    url(r'^instructors_by_date/?$', views.instructors_by_date, name='instructors_by_date'),

    url(r'^export/badges/?$', views.export_badges, name='export_badges'),
    url(r'^export/instructors/?$', views.export_instructors, name='export_instructors'),
    url(r'^export/members/?$', views.export_members, name='export_members'),

    url(r'^reports/workshops_over_time/?$', views.workshops_over_time, name='workshops_over_time'),
    url(r'^reports/learners_over_time/?$', views.learners_over_time, name='learners_over_time'),
    url(r'^reports/instructors_over_time/?$', views.instructors_over_time, name='instructors_over_time'),
    url(r'^reports/instructor_num_taught/?$', views.instructor_num_taught, name='instructor_num_taught'),
    url(r'^reports/all_activity_over_time/?$', views.all_activity_over_time, name='all_activity_over_time'),
    url(r'^reports/workshop_issues/?$', views.workshop_issues, name='workshop_issues'),
    url(r'^reports/instructor_issues/?$', views.instructor_issues, name='instructor_issues'),
    url(r'^reports/duplicates/?$', views.duplicates, name='duplicates'),

    url(r'^revision/(?P<revision_id>[\d]+)/?$', views.object_changes, name='object_changes'),

    url(r'^requests/$', views.all_eventrequests, name='all_eventrequests'),
    url(r'^request/(?P<request_id>\d+)/?$', views.EventRequestDetails.as_view(), name='eventrequest_details'),
    url(r'^request/(?P<request_id>\d+)/discard/?$', views.eventrequest_discard, name='eventrequest_discard'),
    url(r'^request/(?P<request_id>\d+)/accept/?$', views.eventrequest_accept, name='eventrequest_accept'),
    url(r'^request/(?P<request_id>\d+)/assign$', views.eventrequest_assign, name='eventrequest_assign'),
    url(r'^request/(?P<request_id>\d+)/assign/(?P<person_id>[\w\.-]+)$', views.eventrequest_assign, name='eventrequest_assign'),
    url(r'^swc/request/$', views.SWCEventRequest.as_view(), name='swc_workshop_request'),
    url(r'^swc/request/confirm/$', views.SWCEventRequestConfirm.as_view(), name='swc_workshop_request_confirm'),
    url(r'^dc/request/$', views.DCEventRequest.as_view(), name='dc_workshop_request'),
    url(r'^dc/request/confirm/$', views.DCEventRequestConfirm.as_view(), name='dc_workshop_request_confirm'),
    url(r'^dc/request_selforganized/$', views.DCSelfOrganizedEventRequest.as_view(), name='dc_workshop_selforganized_request'),
    url(r'^dc/request_selforganized/confirm/$', views.DCSelfOrganizedEventRequestConfirm.as_view(), name='dc_workshop_selforganized_request_confirm'),
    url(r'^dc_selforganized_requests/$', views.AllDCSelfOrganizedEventRequests.as_view(), name='all_dcselforganizedeventrequests'),
    url(r'^dc_selforganized_request/(?P<request_id>\d+)/?$', views.DCSelfOrganizedEventRequestDetails.as_view(), name='dcselforganizedeventrequest_details'),
    url(r'^dc_selforganized_request/(?P<request_id>\d+)/edit$', views.DCSelfOrganizedEventRequestChange.as_view(), name='dcselforganizedeventrequest_edit'),
    url(r'^dc_selforganized_request/(?P<request_id>\d+)/assign$', views.dcselforganizedeventrequest_assign, name='dcselforganizedeventrequest_assign'),
    url(r'^dc_selforganized_request/(?P<request_id>\d+)/assign/(?P<person_id>[\w\.-]+)$', views.dcselforganizedeventrequest_assign, name='dcselforganizedeventrequest_assign'),

    url(r'^submissions/$', views.AllEventSubmissions.as_view(), name='all_eventsubmissions'),
    url(r'^submission/(?P<submission_id>\d+)/?$', views.EventSubmissionDetails.as_view(), name='eventsubmission_details'),
    url(r'^submission/(?P<submission_id>\d+)/fix/?$', views.EventSubmissionFix.as_view(), name='eventsubmission_fix'),
    url(r'^submission/(?P<submission_id>\d+)/discard/?$', views.eventsubmission_discard, name='eventsubmission_discard'),
    url(r'^submission/(?P<submission_id>\d+)/accept/?$', views.eventsubmission_accept, name='eventsubmission_accept'),
    url(r'^submission/(?P<submission_id>\d+)/assign$', views.eventsubmission_assign, name='eventsubmission_assign'),
    url(r'^submission/(?P<submission_id>\d+)/assign/(?P<person_id>[\w\.-]+)$', views.eventsubmission_assign, name='eventsubmission_assign'),
    url(r'^submit/$', views.EventSubmission.as_view(), name='event_submit'),
    url(r'^submit/confirm/$', views.EventSubmissionConfirm.as_view(), name='event_submission_confirm'),

    url(r'^profile_updates/$', views.AllProfileUpdateRequests.as_view(), name='all_profileupdaterequests'),
    url(r'^profile_updates/closed/$', views.AllClosedProfileUpdateRequests.as_view(), name='all_closed_profileupdaterequests'),
    url(r'^profile_update/(?P<request_id>\d+)/?$', views.profileupdaterequest_details, name='profileupdaterequest_details'),
    url(r'^profile_update/(?P<request_id>\d+)/fix/?$', views.ProfileUpdateRequestFix.as_view(), name='profileupdaterequest_fix'),
    url(r'^profile_update/(?P<request_id>\d+)/discard/?$', views.profileupdaterequest_discard, name='profileupdaterequest_discard'),
    url(r'^profile_update/(?P<request_id>\d+)/accept/?$', views.profileupdaterequest_accept, name='profileupdaterequest_accept'),
    url(r'^profile_update/(?P<request_id>\d+)/accept/(?P<person_id>[\w\.-]+)/?$', views.profileupdaterequest_accept, name='profileupdaterequest_accept'),
    url(r'^update_profile/$', views.profileupdaterequest_create, name='profileupdate_request'),
    url(r'^autoupdate_profile/$', views.autoupdate_profile, name='autoupdate_profile'),

    url(r'^request_training/$', views.trainingrequest_create, name='training_request'),
    url(r'^training_requests/$', views.TrainingRequestListView.as_view(), name='all_trainingrequests'),
    url(r'^training_requests/(?P<request_id>\d+)/?$', views.TrainingRequestDetails.as_view(), name='trainingrequest_details'),

    url(r'^todos/(?P<event_ident>[\w-]+)/add$', views.todos_add, name='todos_add'),
    url(r'^todo/(?P<todo_id>\d+)/completed', views.todo_mark_completed, name='todo_mark_completed'),
    url(r'^todo/(?P<todo_id>\d+)/incompleted', views.todo_mark_incompleted, name='todo_mark_incompleted'),
    url(r'^todo/(?P<todo_id>\d+)/edit', views.TodoItemUpdate.as_view(), name='todo_edit'),
    url(r'^todo/(?P<todo_id>\d+)/delete', views.todo_delete, name='todo_delete'),
]
