# Generated by Django 2.1.7 on 2019-09-07 11:16

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def add_new_data_variant(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    DataVariant = apps.get_model("extrequests", "DataVariant")
    dv = "Library data (e.g. MARC, XML, RDF, JSON)"
    DataVariant.objects.create(name=dv, unknown=False)


class Migration(migrations.Migration):
    dependencies = [
        ("extrequests", "0014_auto_20190907_1113"),
    ]

    operations = [
        migrations.RunPython(add_new_data_variant),
    ]
