# Generated by Django 2.2.24 on 2021-12-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extrequests", "0029_auto_20210807_1951"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopinquiryrequest",
            name="administrative_fee",
            field=models.CharField(
                choices=[
                    (
                        "nonprofit",
                        "I am with a government site, university, or other nonprofit. I understand the workshop fee "
                        "as listed on The Carpentries website and agree to follow through on The Carpentries "
                        "invoicing process.",
                    ),
                    (
                        "forprofit",
                        "I am with a corporate or for-profit site. I understand the costs for for-profit organisations "
                        "are four times the price for not-for-profit organisations.",
                    ),
                    (
                        "member",
                        "I am with a Member organisation so the workshop fee does not apply (instructor travel costs "
                        "will still apply for in-person workshops).",
                    ),
                    (
                        "waiver",
                        "I am requesting financial support for the workshop fee (instructor travel costs will still "
                        "apply for in-person workshops)",
                    ),
                ],
                default=None,
                help_text="<a href='https://carpentries.org/workshops/#workshop-cost' target='_blank' rel='noreferrer "
                "nofollow'>The Carpentries website workshop fee listing.</a>",
                max_length=20,
                verbose_name="Which of the following applies to your payment for the administrative fee?",
            ),
        ),
        migrations.AlterField(
            model_name="workshopinquiryrequest",
            name="requested_workshop_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="If your learners are new to programming and primarily interested in working with data, Data"
                " Carpentry is likely the best choice. If your learners are interested in learning more about "
                "programming, including version control and automation, Software Carpentry is likely the best "
                "match. If your learners are people working in library and information related roles interested "
                "in learning data and software skills, Library Carpentry is the best choice. Please visit the "
                '<a href="https://software-carpentry.org/lessons/">Software Carpentry lessons page</a>, '
                '<a href="http://www.datacarpentry.org/lessons/">Data Carpentry lessons page</a>, or the '
                '<a href="https://librarycarpentry.org/lessons/">Library Carpentry lessons page</a> for '
                "more information about any of our lessons. If you're not sure and would like to discuss "
                'with us, please select the "Don\'t know yet" option below.<br class="mb-1">Check all that apply.',
                limit_choices_to={"active": True},
                to="workshops.Curriculum",
                verbose_name="Which Carpentries workshop are you requesting?",
            ),
        ),
    ]
