# Generated by Django 3.2.20 on 2023-08-15 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extrequests", "0030_auto_20211231_1108"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workshopinquiryrequest",
            name="number_attendees",
        ),
    ]
