# Generated by Django 3.2.20 on 2023-10-23 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extrequests", "0032_add_member_affiliation_and_member_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selforganisedsubmission",
            name="member_affiliation",
        ),
        migrations.RemoveField(
            model_name="workshopinquiryrequest",
            name="member_affiliation",
        ),
    ]
