# Generated by Django 5.2.12 on 2026-03-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extrequests", "0036_alter_selforganisedsubmission_code_of_conduct_agreement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selforganisedsubmission",
            name="member_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you are affiliated with a Carpentries member organization, please enter the registration"
                " code associated with the membership or partnership. Your Member Affiliate can provide this.",
                max_length=40,
                verbose_name="Registration code",
            ),
        ),
        migrations.AlterField(
            model_name="workshopinquiryrequest",
            name="member_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you are affiliated with a Carpentries member organization, please enter the registration"
                " code associated with the membership or partnership. Your Member Affiliate can provide this.",
                max_length=40,
                verbose_name="Registration code",
            ),
        ),
    ]
