# Generated by Django 5.2.13 on 2026-04-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extrequests", "0038_alter_selforganisedsubmission_member_code_and_more"),
        ("workshops", "0293_alter_curriculum_carpentry_alter_event_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopinquiryrequest",
            name="requested_workshop_types",
            field=models.ManyToManyField(
                blank=True,
                help_text='If your learners are new to programming and primarily interested in working with data, Data Carpentry is likely the best choice. If your learners are interested in learning more about programming, including version control and automation, Software Carpentry is likely the best match. If your learners are people working in library and information related roles interested in learning data and software skills, Library Carpentry is the best choice. If your learners want to use high performance computing (HPC) systems for research, High Performance Computing Carpentry is likely the best match. Please visit the <a href="https://software-carpentry.org/lessons/">Software Carpentry lessons page</a>, <a href="http://www.datacarpentry.org/lessons/">Data Carpentry lessons page</a>, <a href="https://librarycarpentry.org/lessons/">Library Carpentry lessons page</a>, or the <a href="https://hpcccarpentry.org/lessons">High Performance Computing Carpentry lessons page</a> for more information about any of our lessons. If you\'re not sure and would like to discuss with us, please select the "Don\'t know yet" option below.<br class="mb-1">Check all that apply.',  # noqa: E501
                limit_choices_to={"active": True},
                to="workshops.curriculum",
                verbose_name="Which Carpentries workshop are you requesting?",
            ),
        ),
    ]
