# Generated by Django 5.2.15 on 2026-08-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extrequests", "0040_alter_workshopinquiryrequest_administrative_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopinquiryrequest",
            name="travel_expences_management",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not sure yet."),
                    (
                        "booked",
                        "Hotel and airfare will be booked by site; ground travel and meals/incidentals will be reimbursed within 60 days.",
                    ),
                    ("reimbursed", "All expenses will be booked by instructors and reimbursed within 60 days."),
                    ("online", "Not applicable, as this will be an online workshop."),
                    ("other", "Other:"),
                ],
                default="",
                max_length=20,
                verbose_name="How will you manage travel expenses for Carpentries Instructors?",
            ),
        ),
    ]
