# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 14:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0074_event_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-invoiced', 'Not invoiced'), ('invoiced', 'Invoiced')], default='not-invoiced', max_length=40, verbose_name='Invoice status')),
                ('reason', models.CharField(blank=True, choices=[('admin-fee', 'Workshop administrative fee'), ('admin-fee-expenses', 'Workshop administrative fee plus expenses'), ('partner', 'Partner agreement'), ('affiliate', 'Affiliate agreement'), ('consulting', 'Consulting'), ('', 'Other (enter below)')], default='admin-fee', max_length=40, verbose_name='Reason for invoice')),
                ('reason_other', models.CharField(blank=True, default='', max_length=100, verbose_name='Other reason for invoice')),
                ('date', models.DateField(help_text="YYYY-MM-DD; either event's date or invoice reason date.", verbose_name='Date of invoice subject')),
                ('event_location', models.CharField(blank=True, default='', max_length=100)),
                ('item_id', models.CharField(blank=True, default='', max_length=40, verbose_name='Item ID (if applicable)')),
                ('postal_number', models.CharField(blank=True, default='', max_length=40, verbose_name='PO # (if required)')),
                ('contact_name', models.CharField(help_text='e.g. Dr. Jane Smith - the name of the person to contact at the organization about the invoice', max_length=100, verbose_name='Organization contact name')),
                ('contact_email', models.CharField(max_length=100, verbose_name='Organization contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=100, verbose_name='Organization contact phone #')),
                ('full_address', models.CharField(help_text='e.g. Dr. Jane Smith; University of Florida Ecology Department; 123 University Way; Gainesville, FL 32844', max_length=255, verbose_name='Full address to invoice')),
                ('amount', models.DecimalField(decimal_places=2, help_text='e.g. 1992.33 ', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Full invoice amount')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'US Dollars'), ('GBP', 'UK Pounds'), ('EUR', 'Euros'), ('', 'Other (enter below)')], default='USD', max_length=40)),
                ('currency_other', models.CharField(blank=True, default='', max_length=100, verbose_name='Other currency')),
                ('breakdown', models.TextField(blank=True, default='', help_text='e.g. 1250.00 workshop fee; 742.33 Instructor, Pat Li, travel expenses', verbose_name='Notes on invoice breakdown')),
                ('vendor_form_required', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Will check with contact and submit info if needed')], default='no', max_length=10, verbose_name='Do vendor/supplier forms need to be submitted?')),
                ('vendor_form_link', models.URLField(blank=True, default='', verbose_name='Link to vendor/supplier forms')),
                ('form_W9', models.BooleanField(verbose_name='Organization needs a W-9 form')),
                ('receipts_sent', models.CharField(choices=[('email', 'Via email'), ('shared', 'In a Google Drive or other shared location'), ('not-yet', "Haven't sent yet"), ('na', 'Not applicable')], default='not-yet', max_length=40, verbose_name='Any required receipts sent?')),
                ('shared_receipts_link', models.URLField(blank=True, default='', help_text='e.g. link to Google drive folder', verbose_name='Link to receipts in shared location')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Any other notes')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshops.Event')),
                ('organization', models.ForeignKey(help_text='e.g. University of Florida Ecology Department', on_delete=django.db.models.deletion.PROTECT, to='workshops.Host', verbose_name='Organization to invoice')),
            ],
        ),
    ]
