# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0082_add_hackathon_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(help_text="<ul><li><i>stalled</i> — for events with lost contact with the host or TTT events that aren't running.</li><li><i>unresponsive</i> – for events whose hosts and/or organizers aren't going to send us attendance data.</li></ul>", to='workshops.Tag'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='approx_attendees',
            field=models.CharField(choices=[('1-20', '1-20 (one room, two instructors)'), ('20-40', '20-40 (one room, two instructors)'), ('40-80', '40-80 (two rooms, four instructors)'), ('80-120', '80-120 (three rooms, six instructors)')], default='20-40', help_text="This number doesn't need to be precise, but will help us decide how many instructors your workshop will need.Each workshop must have at least two instructors.", max_length=40, verbose_name='Approximate number of Attendees'),
        ),
    ]
