# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 15:12
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F
from django.db.models.functions import Lower


def lowercase_emails(apps, schemat_editor):
    """Replace '.' with '_' in every username."""
    Person = apps.get_model('workshops', 'Person')
    # first: annotate everyone with their email lower-cased
    persons = Person.objects.all().annotate(lower_email=Lower('email'))
    # then: update the email to the lower-cased email
    persons.update(email=F('lower_email'))


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0083_auto_20160323_1554'),
    ]

    operations = [
        migrations.RunPython(lowercase_emails),
    ]
