# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0083_auto_20160323_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='instructors_post',
            field=models.URLField(blank=True, default='', verbose_name='Post-workshop assessment survey for instructors'),
        ),
    ]
