# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0098_auto_20160520_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Human language of instruction during the workshop.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.Language'),
        ),
    ]
