# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0104_auto_20160629_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Personal website'),
        ),
    ]
