# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0107_auto_20160701_0408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgedomain',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='github',
            field=models.CharField(max_length=100, null=True, blank=True, verbose_name='GitHub username'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='previous_experience_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation of your previous experience in teaching'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='previous_training_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation of your previous training in teaching'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='affiliation',
            field=models.CharField(max_length=100, verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='family',
            field=models.CharField(max_length=100, verbose_name='Family name (surname)'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='location',
            field=models.CharField(help_text='please give city, and province or state if applicable', max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='personal',
            field=models.CharField(max_length=100, verbose_name='Personal (given) name'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='previous_training',
            field=models.CharField(choices=[('none', 'None'), ('hours', 'A few hours'), ('days', 'A few days'), ('course', 'A certification or short course'), ('full', 'A full degree'), ('other', 'Other (enter below)')], default='none', max_length=40, verbose_name='Previous training in teaching'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='programming_language_usage_frequency',
            field=models.CharField(choices=[('daily', 'Every day'), ('weekly', 'A few times a week'), ('monthly', 'A few times a month'), ('yearly', 'A few times a year'), ('not-much', 'Never or almost never')], default='daily', max_length=40, verbose_name='How frequently do you use Python, R or Matlab?'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='teaching_frequency_expectation',
            field=models.CharField(choices=[('not-at-all', 'Not at all'), ('yearly', 'Once a year'), ('monthly', 'Several times a year'), ('often', 'Primary occupation'), ('other', 'Other (enter below)')], default='not-at-all', max_length=40, verbose_name='How often would you expect to teach on Software or Data Carpentry Workshops after this training?'),
        ),
    ]
