# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0115_auto_20160812_2056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('event', 'person', 'role', 'url')]),
        ),
    ]
