# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-01 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0120_auto_20161023_1345'),
        ('workshops', '0120_merge'),
    ]

    operations = [
    ]
