# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-18 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0123_auto_20161212_1122'),
        ('workshops', '0123_auto_20161218_0538'),
    ]

    operations = [
    ]
