# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 09:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0125_trainingrequest_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='github',
            field=models.CharField(blank=True, help_text='Please put only a single username here.', max_length=40, null=True, unique=True, validators=[django.core.validators.RegexValidator('[, ]+', 'Spaces or commas are disallowed.', inverse_match=True)], verbose_name='GitHub username'),
        ),
        migrations.AlterField(
            model_name='profileupdaterequest',
            name='github',
            field=models.CharField(blank=True, default='', help_text='Please put only a single username here.', max_length=100, validators=[django.core.validators.RegexValidator('[, ]+', 'Spaces or commas are disallowed.', inverse_match=True)], verbose_name='GitHub username'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='github',
            field=models.CharField(blank=True, help_text='Please put only a single username here.', max_length=100, null=True, validators=[django.core.validators.RegexValidator('[, ]+', 'Spaces or commas are disallowed.', inverse_match=True)], verbose_name='GitHub username'),
        ),
    ]
