# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-02-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0131_trainingrequest_remove_fields_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='location',
            field=models.CharField(help_text='Please give city, and province or state if applicable. Do not share a full mailing address.', max_length=100, verbose_name='Location'),
        ),
    ]
