# Generated by Django 2.0.5 on 2018-05-19 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0134_mentor_mentee_badges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['awarded']},
        ),
        migrations.AlterModelOptions(
            name='eventrequest',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventsubmission',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['family', 'personal']},
        ),
        migrations.AlterModelOptions(
            name='trainingrequest',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='person',
            name='publish_profile',
            field=models.BooleanField(default=False, help_text='Allow to share profile with The Carpentries website according to the <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html" target="_blank">Privacy Policy</a>.', verbose_name='Consent to making profile public'),
        ),
        migrations.AddField(
            model_name='profileupdaterequest',
            name='may_contact',
            field=models.BooleanField(default=True, help_text='Allow to contact from The Carpentries according to the <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html" target="_blank">Privacy Policy</a>.'),
        ),
        migrations.AddField(
            model_name='profileupdaterequest',
            name='publish_profile',
            field=models.BooleanField(default=False, help_text='Allow to share profile with The Carpentries website according to the <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html" target="_blank">Privacy Policy</a>.', verbose_name='Consent to making profile public'),
        ),
        migrations.AlterField(
            model_name='award',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshops.Badge'),
        ),
        migrations.AlterField(
            model_name='award',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dcselforganizedeventrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Backlink to the request that created this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.EventRequest'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.Language', verbose_name='What human language do you want the workshop to be run in?'),
        ),
        migrations.AlterField(
            model_name='eventsubmission',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='domains',
            field=models.ManyToManyField(blank=True, help_text='Please check all that apply.', limit_choices_to=models.Q(_negated=True, name__startswith="Don't know yet"), to='workshops.KnowledgeDomain', verbose_name='Areas of expertise'),
        ),
        migrations.AlterField(
            model_name='person',
            name='may_contact',
            field=models.BooleanField(default=True, help_text='Allow to contact from The Carpentries according to the <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html" target="_blank">Privacy Policy</a>.'),
        ),
        migrations.AlterField(
            model_name='profileupdaterequest',
            name='domains',
            field=models.ManyToManyField(blank=True, help_text='Please check all that apply.', limit_choices_to=models.Q(_negated=True, name__startswith="Don't know yet"), to='workshops.KnowledgeDomain', verbose_name='Areas of expertise'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshops.Lesson'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshops.Event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshops.Role'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshops.Event'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='event',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(tags__name='TTT'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.Event', verbose_name='Training'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='domains',
            field=models.ManyToManyField(blank=True, help_text='Please check all that apply.', limit_choices_to=models.Q(_negated=True, name__startswith="Don't know yet"), to='workshops.KnowledgeDomain', verbose_name='Areas of expertise'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Matched Trainee'),
        ),
    ]
