# Generated by Django 2.0.5 on 2018-05-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0140_NullableGithubUsernameField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='data_types',
            field=models.CharField(blank=True, choices=[('survey', 'Survey data (ecology, biodiversity, social science)'), ('genomic', 'Genomic data'), ('geospatial', 'Geospatial data'), ('text-mining', 'Text mining'), ('', 'Other:')], max_length=40, verbose_name='We currently have developed or are developing workshops focused on four types of data. Please let us know which workshop would best suit your needs.'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='travel_reimbursement',
            field=models.CharField(blank=True, choices=[('', "Don't know yet."), ('book', 'Book travel through our university or program.'), ('reimburse', 'Book their own travel and be reimbursed.'), ('', 'Other:')], default='', max_length=40, verbose_name="How will instructors' travel and accommodations be managed?"),
        ),
        migrations.AlterField(
            model_name='profileupdaterequest',
            name='gender',
            field=models.CharField(choices=[('U', 'Prefer not to say'), ('F', 'Female'), ('M', 'Male'), ('O', 'Other:')], default='U', max_length=1),
        ),
    ]
