# Generated by Django 2.0.5 on 2018-07-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0142_auto_20180704_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='group_name',
            field=models.CharField(blank=True, default='', help_text='If you are scheduled to receive training at a member site, please enter the group name you were provided. Otherwise please leave this blank.', max_length=100, verbose_name='Group name'),
        ),
    ]
