# Generated by Django 2.1 on 2018-09-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0149_active_field_to_state_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='seats_instructor_training',
            field=models.PositiveIntegerField(default=0, help_text='Number of seats in instructor trainings'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='state',
            field=models.CharField(choices=[('p', 'Pending'), ('d', 'Discarded'), ('a', 'Accepted')], default='p', max_length=1),
        ),
    ]
