# Generated by Django 2.1 on 2018-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0151_auto_20180902_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='open_TTT_applications',
            field=models.BooleanField(blank=True, default=False, help_text="If this event is TTT, you can mark it as 'open applications' which means that people not associated with this event's member sites can also take part in this event.", verbose_name='TTT Open applications'),
        ),
    ]
