# Generated by Django 2.1 on 2018-09-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0152_event_open_ttt_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='member_sites',
            field=models.ManyToManyField(blank=True, help_text='TTT Member organizations', to='workshops.Membership', verbose_name='Memberships associated with this <b>TTT</b> event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='open_TTT_applications',
            field=models.BooleanField(blank=True, default=False, help_text="If this event is <b>TTT</b>, you can mark it as 'open applications' which means that people not associated with this event's member sites can also take part in this event.", verbose_name='TTT Open applications'),
        ),
    ]
