# Generated by Django 2.1 on 2018-09-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0155_auto_20180916_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='score_manual',
            field=models.IntegerField(blank=True, help_text="Leave blank if you don't want to score this application.", null=True, verbose_name='Application manual score (can be negative)'),
        ),
    ]
