# Generated by Django 2.1 on 2018-10-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0156_auto_20180927_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
