# Generated by Django 2.1.2 on 2018-10-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0161_auto_20181028_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='event',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
