# Generated by Django 2.1.2 on 2018-11-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0163_auto_20181106_1416'),
    ]

    database_operations = [
    ]

    state_operations = [
        migrations.DeleteModel('DataAnalysisLevel'),
        migrations.DeleteModel('DCWorkshopTopic'),
        migrations.DeleteModel('DCWorkshopDomain'),
        migrations.DeleteModel('ProfileUpdateRequest'),
        migrations.DeleteModel('EventRequest'),
        migrations.DeleteModel('EventSubmission'),
        migrations.DeleteModel('DCSelfOrganizedEventRequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoprequest',
            name='academic_levels',
            field=models.ManyToManyField(help_text='If you know the academic level(s) of your attendees, indicate them here.', to='workshops.AcademicLevel', verbose_name="Attendees' academic level / career stage"),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=database_operations,
        ),
    ]
