# Generated by Django 2.1.2 on 2018-11-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0164_remove_nonversioned_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lesson_publication_consent',
            field=models.CharField(blank=True, choices=[('yes-profile', 'Yes, and use the name associated with my profile'), ('yes-orcid', 'Yes, and use the name associated with my ORCID profile'), ('yes-github', 'Yes, and only use my GitHub handle'), ('no', 'No')], default='no', help_text='When we publish our lessons, we like to include everyone who has contributed via pull request as an author. If you do make any contributions, would you like to be included as an author when we publish the lesson?', max_length=40, verbose_name='Do you consent to have your name or identity associated with lesson publications?'),
        ),
    ]
