# Generated by Django 2.1.2 on 2018-11-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0166_new_tags_ITT_LMO_LSO'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoprequest',
            name='centrally_organized_fee',
            field=models.CharField(choices=[('nonprofit', 'I am with a government site, university, or other nonprofit. I understand the workshop fee of US$2500, and agree to follow through on The Carpentries invoicing process.'), ('forprofit', 'I am with a corporate or for-profit site. I understand The Carpentries staff will contact me about workshop fees. I will follow through on The Carpentries invoicing process for the agreed upon fee.'), ('member', 'I am with a Member Organisation so the workshop fee does not apply (Instructor travel costs will still apply).'), ('waiver', 'I am requesting a waiver of the workshop fee (Instructor travel costs will still apply).')], default='nonprofit', max_length=20, verbose_name='Which of the following applies to your payment for the administrative fee?'),
        ),
    ]
