# Generated by Django 2.1.2 on 2018-12-25 17:51

from django.db import migrations


def add_LC_instructor_badge(apps, schema_editor):
    """Add Library Carpentry Instructor badge."""
    Badge = apps.get_model('workshops', 'Badge')
    b = Badge(name='lc-instructor', title='Library Carpentry Instructor',
              criteria='Teaching at Library Carpentry workshops or online')
    b.save()


def remove_LC_instructor_badge(apps, schema_editor):
    """Remove Library Carpentry Instructor badge."""
    Badge = apps.get_model('workshops', 'Badge')
    Badge.objects.get(name='lc-instructor').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0170_auto_20181209_0914'),
    ]

    operations = [
        migrations.RunPython(add_LC_instructor_badge,     # forward
                             remove_LC_instructor_badge)  # reverse
    ]
