# Generated by Django 2.1.2 on 2018-12-26 08:49

from django.db import migrations


def add_AMY_sites(apps, schema_editor):
    """Add AMY sites to `django.contrib.sites`."""
    Site = apps.get_model('sites', 'Site')

    data = [
        dict(domain='amy.software-carpentry.org', name='AMY'),
        dict(domain='amy.carpentries.org', name='AMY'),
    ]

    # It's required to use 'update_or_create', because by default the
    # django.contrib.sites installs `example.com` Site with pk=1. So, if it's
    # present, we overwrite its fields, otherwise simply add it to the
    # database.

    # first site: amy.software-carpentry.org
    Site.objects.update_or_create(pk=1, defaults=data[0])

    # second site: amy.carpentries.org
    Site.objects.update_or_create(pk=2, defaults=data[1])


def remove_AMY_sites(apps, schema_editor):
    """Remove AMY sites from `django.contrib.sites`."""
    Site = apps.get_model('sites', 'Site')
    domains = ['amy.software-carpentry.org', 'amy.carpentries.org']
    Site.objects.filter(domain__in=domains).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0171_add_LC_instructor_badge'),
    ]

    operations = [
        migrations.RunPython(add_AMY_sites,     # forward
                             remove_AMY_sites)  # reverse
    ]
