# Generated by Django 2.1.2 on 2018-12-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0173_migrate_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='trainingrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='workshoprequest',
            name='admin_comment',
        ),
    ]
