# Generated by Django 2.1.2 on 2018-12-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0174_remove_notes_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingrequest',
            old_name='comment',
            new_name='user_notes',
        ),
        migrations.RenameField(
            model_name='workshoprequest',
            old_name='comment',
            new_name='user_notes',
        ),
    ]
