# Generated by Django 2.1.2 on 2019-01-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0175_unify_user_note_field_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='group_name',
            field=models.CharField(blank=True, default='', help_text='If you are scheduled to receive training at a member site, please enter the same code you were given to register on Eventbrite. Otherwise please leave this blank.', max_length=100, verbose_name='Registration Code'),
        ),
    ]
