# Generated by Django 2.1.2 on 2019-01-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0176_auto_20190115_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicerequest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='invoicerequest',
            name='organization',
        ),
        migrations.DeleteModel(
            name='InvoiceRequest',
        ),
    ]
