# Generated by Django 2.1.2 on 2019-02-13 16:40

import json

from django.db import migrations


def update_language_names(apps, schema_editor):
    """`registry.json` in some cases provides multiple descriptions for the
    same language. This will update the names of these languages in the
    database with proper punctuation between description choices.

    For example: language coded as "nl" is described as ["Dutch", "Flemish"].
    These are separate but similar languages. They used to be named
    "Dutch Flemish" in database, but that is changed here to "Dutch, Flemish".

    See https://github.com/swcarpentry/amy/issues/1298 for more info.

    Additionally, the registry was updated with 2018-08 version, and so the
    database is updated with other languages as well."""

    Language = apps.get_model('workshops', 'Language')

    # read list of languages
    with open('amy/workshops/migrations/data/registry.json', encoding='utf-8') as f:
        languages_json = json.load(f)

    for language in languages_json:
        if language['Type'] == 'language' and len(language['Subtag']) <= 2:
            # update language (found by subtag) with a new name,
            # or create if it doesn't exist yet
            Language.objects.update_or_create(
                subtag=language['Subtag'],
                defaults=dict(
                    name=', '.join(language['Description']),
                ),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0177_auto_20190130_0815'),
    ]

    operations = [
        migrations.RunPython(update_language_names),
    ]
