# Generated by Django 2.1.2 on 2019-02-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0178_auto_20190213_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingrequest',
            old_name='underrepresented',
            new_name='underrepresented_details',
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='underrepresented_details',
            field=models.CharField(blank=True, default='', help_text="This response is optional and doesn't impact your application's ranking.", max_length=255, verbose_name="If you are comfortable doing so, please share more details. Your response is optional, and these details will not impact your application's ranking."),
        ),
    ]
