# Generated by Django 2.1.2 on 2019-02-21 15:47

from django.db import migrations, models


def fill_underrepresented(apps, schema_editor):
    """A new field, `underrepresented` (yes|no|undisclosed), is created and
    requires filling up with data based on `underrepresented_details`
    contents."""

    TrainingRequest = apps.get_model('workshops', 'TrainingRequest')

    # go through all training requests
    for req in TrainingRequest.objects.all():
        # treat "underrepresented_details" as a string (previously it could
        # have been null-ed)
        try:
            # if there's still something in details after stripping it off of
            # whitespace, then probably someone gave a valid reason for being
            # underrepresented and we should reflect that
            if req.underrepresented_details.strip():
                req.underrepresented = "yes"
                req.save()
        except AttributeError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0179_auto_20190221_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='underrepresented',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('undisclosed', 'Prefer not to say')], default='undisclosed', help_text='The Carpentries strives to increase opportunities for underrepresented groups to join our team.', max_length=20, verbose_name='I self-identify as a member of a group that is under-represented in research and/or computing.'),
        ),
        migrations.RunPython(fill_underrepresented),
    ]
