# Generated by Django 2.1.7 on 2019-03-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0181_LC_TrainingRequirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendance',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Manually entered attendance; for actual attendance, this number is compared with number of Learner tasks, and the higher value is shown.', verbose_name='Manual attendance'),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='attendance',
            new_name='manual_attendance',
        ),
    ]
