# Generated by Django 2.1.7 on 2019-04-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0182_auto_20190317_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoprequest',
            name='host_responsibilities',
            field=models.BooleanField(default=False, verbose_name='I understand <a href="https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#host-checklist">the responsibilities of the workshop host</a>,including recruiting local helpers to support the workshop (1 helper for every 8-10 learners).'),
        ),
    ]
