# Generated by Django 2.1.7 on 2019-04-09 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0182_auto_20190317_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='duplication_reviewed_on',
            field=models.DateTimeField(blank=True, help_text='Set this to a newer / actual timestamp when Person is reviewed by admin.', null=True, verbose_name='Timestamp of duplication review by admin'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
