# Generated by Django 2.1.7 on 2019-07-18 15:37

from django.db import migrations, models
import django.db.models.deletion


def extend_current_Curricula(apps, schema_editor):
    """Update existing Curricula with new fields."""

    Curriculum = apps.get_model('workshops', 'Curriculum')

    data = {
        'swc-python': dict(
            carpentry='SWC',
            description='Software Carpentry (shell, git, Python)',
            other=False,
        ),
        'swc-r': dict(
            carpentry='SWC',
            description='Software Carpentry (shell, git, R)',
            other=False,
        ),
        'swc-es-python': dict(
            carpentry='SWC',
            description='Software Carpentry in Spanish (shell, git, Python)',
            other=False,
        ),
        'swc-es-r': dict(
            carpentry='SWC',
            description='Software Carpentry in Spanish (shell, git, R)',
            other=False,
        ),
        'swc-other': dict(
            carpentry='SWC',
            description='Software Carpentry (other)',
            other=True,
        ),
        'dc-ecology-python': dict(
            carpentry='DC',
            description='Data Carpentry (Ecology with Python)',
            other=False,
        ),
        'dc-ecology-r': dict(
            carpentry='DC',
            description='Data Carpentry (Ecology with R)',
            other=False,
        ),
        'dc-genomics': dict(
            carpentry='DC',
            description='Data Carpentry (Genomics)',
            other=False,
        ),
        'dc-geospatial': dict(
            carpentry='DC',
            description='Data Carpentry (Geospatial)',
            other=False,
        ),
        'dc-socsci-python': dict(
            carpentry='DC',
            description='Data Carpentry (Social Sciences with Python)',
            other=False,
        ),
        'dc-socsci-r': dict(
            carpentry='DC',
            description='Data Carpentry (Social Sciences with R)',
            other=False,
        ),
        'dc-other': dict(
            carpentry='DC',
            description='Data Carpentry (other)',
            other=True,
        ),
        'lc': dict(
            carpentry='LC',
            description='Library Carpentry (Intro to Data, Unix Shell, Git, and/or OpenRefine)',
            other=False,
        ),
        'lc-other': dict(
            carpentry='LC',
            description='Library Carpentry (other)',
            other=True,
        ),
        'unknown': dict(
            carpentry='',
            description="Don't know yet",
            other=False,
        ),
    }

    for slug, defaults in data.items():
        Curriculum.objects.filter(slug=slug).update(**defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0185_add_InfoSource'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='carpentry',
            field=models.CharField(blank=True, choices=[('SWC', 'Software Carpentry'), ('DC', 'Data Carpentry'), ('LC', 'Library Carpentry'), ('', 'unspecified / irrelevant')], default='', max_length=5, verbose_name='Which Carpentry does this curriculum belong to?'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='description',
            field=models.TextField(blank=True, default='', help_text='You can enter Markdown. It will be shown as a hover or popup over the curriculum entry on forms.', max_length=300, verbose_name='Curriculum longer description'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='other',
            field=models.BooleanField(blank=True, default=False, help_text="Mark this curriculum record as '*Other' (eg. 'SWC Other', 'DC Other', or simply 'Other')", verbose_name="Field marked as 'Other'"),
        ),
        migrations.RunPython(extend_current_Curricula),
    ]
