# Generated by Django 2.1.7 on 2019-07-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0187_WorkshopRequest_rename_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoprequest',
            name='additional_contact',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Is there anyone you would like included on communication for this workshop? Please provide contact name(s) and e-mail(s) address'),
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='carpentries_info_source',
            field=models.ManyToManyField(blank=True, to='workshops.InfoSource', verbose_name='How did you hear about The Carpentries?'),
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='carpentries_info_source_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other source for information about The Carpentries'),
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='institution_other_URL',
            field=models.URLField(blank=True, default='', help_text='Please provide URL.', max_length=255, verbose_name='If your institutional affiliation is not listed, please enter the website'),
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='institution_restrictions',
            field=models.CharField(choices=[('no_restrictions', 'No restrictions'), ('', 'Other:')], default='', max_length=20, verbose_name='Our instructors live, teach, and travel globally. We understand that institutions may have citizenship or other requirements for employees or volunteers who facilitate workshops. If your institution fits this description, please share your requirements or note that there are no restrictions.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='institution_restrictions_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other (institution restrictions)'),
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='preferred_dates',
            field=models.DateField(blank=True, help_text='Our workshops typically run two full days. Please select your preferred first day for the workshop. If you do not have exact dates or are interested in an alternative schedule, please indicate so below. Because we need to coordinate with instructors, a minimum of 2-3 months lead time is required for workshop planning.', null=True, verbose_name='Preferred dates'),
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='public_event',
            field=models.CharField(choices=[('public', 'Yes, this workshop is open to the public'), ('closed', 'No, this is a closed event'), ('', 'Other:')], default='', help_text='Many of our workshops restrict registration to learners from the hosting institution. If your workshop will be open to registrants outside of your institution please let us know below.', max_length=20, verbose_name='Is this workshop open to the public?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='public_event_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other (workshop open to the public)'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='administrative_fee',
            field=models.CharField(choices=[('nonprofit', 'I am with a government site, university, or other nonprofit. I understand the workshop fee of US$2500, and agree to follow through on The Carpentries invoicing process.'), ('forprofit', 'I am with a corporate or for-profit site. I understand The Carpentries staff will contact me about workshop fees. I will follow through on The Carpentries invoicing process for the agreed upon fee.'), ('member', 'I am with a Member Organisation so the workshop fee does not apply (Instructor travel costs will still apply).'), ('waiver', 'I am requesting a scholarship for the workshop fee (Instructor travel costs will still apply).')], default='nonprofit', max_length=20, verbose_name='Which of the following applies to your payment for the administrative fee?'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='family',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Family name (surname)'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='institution_other_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='If your institutional affiliation is not listed, please enter the name'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='language',
            field=models.ForeignKey(help_text='Our workshops are offered primarily in English, with a few of our lessons available in Spanish. While materials are mainly in English, we know it can be valuable to have an instructor who speaks the native language of the learners. We will attempt to locate Instructors speaking a particular language, but cannot guarantee the availability of non-English speaking Instructors.', on_delete=django.db.models.deletion.PROTECT, to='workshops.Language', verbose_name='What language will this workshop be conducted in?'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='location',
            field=models.CharField(default='', help_text='City, state, or province.', max_length=255, verbose_name='Workshop location'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='number_attendees',
            field=models.CharField(choices=[('10-40', '10-40 (one room, two instructors)'), ('40-80', '40-80 (two rooms, four instructors)'), ('80-120', '80-120 (three rooms, six instructors)')], default='10-40', help_text="This number doesn't need to be precise, but will help us decide how many instructors your workshop will need. Each workshop must have at least two instructors.", max_length=15, verbose_name='Anticipated number of attendees'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='other_preferred_dates',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='If your dates are not set, please provide more information below'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='requested_workshop_types',
            field=models.ManyToManyField(help_text='If your learners are new to programming and primarily interested in working with data, Data Carpentry is likely the best choice. If your learners are interested in learning more about programming, including version control and automation, Software Carpentry is likely the best match. If your learners are people working in library and information related roles interested in learning data and software skills, Library Carpentry is the best choice. Please visit the <a href="https://software-carpentry.org/lessons/">Software Carpentry lessons page</a>, <a href="http://www.datacarpentry.org/lessons/">Data Carpentry lessons page</a>, or the <a href="https://librarycarpentry.org/lessons/">Library Carpentry lessons page</a> for more information about any of our lessons.', limit_choices_to={'active': True}, to='workshops.Curriculum', verbose_name='Which Carpentry workshop are you requesting?'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='scholarship_circumstances',
            field=models.TextField(blank=True, help_text='Required only if you request a scholarship.', verbose_name='Please explain the circumstances for your scholarship request'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='organization_type',
            field=models.CharField(choices=[('self', 'Self-organized'), ('central', 'Centrally-organized')], default='central', max_length=15, verbose_name='Will this be a self-organized or centrally-organized workshop?'),
        ),
    ]
