# Generated by Django 2.1.7 on 2019-07-28 11:18

from django.db import migrations, models
import django.db.models.deletion


def new_mix_match_curriculum(apps, schema_editor):
    """Add new mix & match Curriculum entry."""
    Curriculum = apps.get_model('workshops', 'Curriculum')
    Curriculum.objects.create(
        name='Mix & Match',
        description='Workshop has mixed curriculum, e.g. without programming, or only git, etc.',
        active=True,
        other=False,
        unknown=False,
        mix_match=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0189_auto_20190725_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='mix_match',
            field=models.BooleanField(blank=True, default=False, help_text="Mark this curriculum record as 'Mix & Match'.There can be only one such record in the database.", verbose_name='Mix & Match'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='institution',
            field=models.ForeignKey(blank=True, help_text="If your institution isn't on the list, enter its name below the list.", null=True, on_delete=django.db.models.deletion.PROTECT, to='workshops.Organization', verbose_name='Institutional affiliation'),
        ),
        migrations.RunPython(new_mix_match_curriculum),
    ]
