# Generated by Django 2.1.7 on 2019-08-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0192_auto_20190811_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoprequest',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='workshoprequest',
            name='self_organized_github',
        ),
    ]
