# Generated by Django 2.1.7 on 2019-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0194_auto_20190818_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lessons',
            field=models.ManyToManyField(blank=True, help_text='Specific lessons covered during the event', to='workshops.Lesson', verbose_name='Lessons covered'),
        ),
    ]
