# Generated by Django 2.1.7 on 2019-08-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0195_event_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoprequest',
            name='public_event',
            field=models.CharField(choices=[('public', 'This event is open to the public.'), ('closed', 'This event is open primarily to the people inside of my institution.'), ('other', 'Other:')], default='', help_text='Many of our workshops restrict registration to learners from the hosting institution. If your workshop will be open to registrants outside of your institution please let us know below.', max_length=20, verbose_name='Is this workshop open to the public?'),
        ),
    ]
