# Generated by Django 2.1.7 on 2019-08-25 15:52

from django.db import migrations


def add_circuits(apps, schema_editor):
    Tag = apps.get_model('workshops', 'Tag')
    Tag.objects.create(
        name='Circuits',
        details="Events with only partial Carpentries curriculum",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0197_auto_20190822_1908'),
    ]

    operations = [
        migrations.RunPython(add_circuits),
    ]
