# Generated by Django 2.1.7 on 2019-09-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0199_auto_20190830_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoprequest',
            name='additional_contact',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Is there anyone you would like included on communication for this workshop? Please provide e-mail addresses.'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='carpentries_info_source',
            field=models.ManyToManyField(blank=True, help_text='Check all that apply.', to='workshops.InfoSource', verbose_name='How did you hear about The Carpentries?'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='family',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Family (last) name'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='institution_department',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Department/School/Library affiliation (if applicable)'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='institution_restrictions',
            field=models.CharField(choices=[('no_restrictions', 'No restrictions'), ('other', 'Other:')], default='', max_length=20, verbose_name='Our instructors live, teach, and travel globally. We understand that institutions may have citizenship, confindentiality agreements or other requirements for employees or volunteers who facilitate workshops. If your institution fits this description, please share your requirements or note that there are no restrictions.'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='language',
            field=models.ForeignKey(help_text='Our workshops are offered primarily in English, with a few of our lessons available in Spanish. While materials are mainly in English, we know it can be valuable to have an instructor who speaks the native language of the learners. We will attempt to locate Instructors speaking a particular language, but cannot guarantee the availability of non-English speaking Instructors.', on_delete=django.db.models.deletion.PROTECT, to='workshops.Language', verbose_name='What is the preferred language of communication for the workshop?'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='personal',
            field=models.CharField(max_length=255, verbose_name='Personal (first) name'),
        ),
    ]
