# Generated by Django 2.1.7 on 2019-09-07 11:14

from django.db import migrations, models


def add_new_infosource(apps, schema_editor):
    InfoSource = apps.get_model('workshops', 'InfoSource')
    InfoSource.objects.create(name='I am already a part of The Carpentries '
                                   'community')


def add_new_academic_level(apps, schema_editor):
    AcademicLevel = apps.get_model('workshops', 'AcademicLevel')
    AcademicLevel.objects.create(name='Staff')


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0200_auto_20190907_1113'),
    ]

    operations = [
        migrations.RunPython(add_new_infosource),
        migrations.RunPython(add_new_academic_level),
    ]
