# Generated by Django 2.2.5 on 2019-09-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0185_revamp_lesson_publication_consent'),
        ('workshops', '0201_auto_20190907_1114'),
    ]

    operations = [
    ]
