# Generated by Django 2.2.5 on 2019-09-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0202_merge_20190907_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoprequest',
            name='scholarship_circumstances',
            field=models.TextField(blank=True, help_text='Required only if you request a scholarship.', verbose_name='We have a limited number of scholarships available. Please explain the circumstances for your scholarship request and let us know what budget you have towards The Carpentries workshop fees.'),
        ),
    ]
