# Generated by Django 2.2.5 on 2019-09-15 08:15

from django.db import migrations, models


def update_trainingrequest_review_process(apps, schema_editor):
    TrainingRequest = apps.get_model('workshops', 'TrainingRequest')
    qs = TrainingRequest.objects.filter(review_process='')

    # 1. update review process for every Training Request that has a code
    qs.exclude(group_name='').update(review_process='preapproved')

    # 2. update review process for every Training Request that has no code
    qs.filter(group_name='').update(review_process='open')


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0203_auto_20190914_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='review_process',
            field=models.CharField(choices=[('preapproved', 'Pre-approved Registration'), ('open', 'Open Training Application')], default='', max_length=20, verbose_name='Application Type'),
        ),
        migrations.RunPython(update_trainingrequest_review_process),
        migrations.AlterField(
            model_name='trainingrequest',
            name='group_name',
            field=models.CharField(blank=True, default='', help_text='If you have been given a registration code through a Carpentries member site or for a specific scheduled event, please enter it here:', max_length=100, verbose_name='Registration Code'),
        ),
    ]
