# Generated by Django 2.2.5 on 2019-12-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0204_trainingrequest_review_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('U', 'Prefer not to say (undisclosed)'), ('F', 'Female'), ('V', 'Gender variant / non-conforming'), ('M', 'Male'), ('O', 'Other: ')], default='U', max_length=1),
        ),
    ]
