# Generated by Django 2.2.5 on 2019-12-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0205_auto_20191230_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='secondary_email',
            field=models.EmailField(blank=True, default='', help_text='This is an optional, secondary email address we can use to contact you.', max_length=254, verbose_name='Secondary email address'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='secondary_email',
            field=models.EmailField(blank=True, default='', help_text='This is an optional, secondary email address we can use to contact you.', max_length=254, verbose_name='Secondary email address'),
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='secondary_email',
            field=models.EmailField(blank=True, default='', help_text='This is an optional, secondary email address we can use to contact you.', max_length=254, verbose_name='Secondary email address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, help_text='Primary email address, used for communication and as a login.', max_length=100, null=True, unique=True, verbose_name='Email address'),
        ),
    ]
