# Generated by Django 2.2.5 on 2019-12-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0206_auto_20191231_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogress',
            name='discarded',
            field=models.BooleanField(default=False, help_text='Check when the trainee has gone silent or passed their training deadline. Discarded items are not deleted permanently. If you want to remove this record, click red "delete" button.', verbose_name='Discarded'),
        ),
    ]
