# Generated by Django 2.2.9 on 2020-01-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0207_auto_20191229_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text="Sorting priority (ascending order). Entries with lower number will appear first on the list. If entries have the same number, they're sorted by name."),
        ),
    ]
