# Generated by Django 2.2.9 on 2020-01-24 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0209_tags_sorting_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='administrator',
            field=models.ForeignKey(blank=True, help_text='Lesson Program administered for this workshop.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrator', to='workshops.Organization'),
        ),
    ]
