# Generated by Django 4.2.19 on 2025-02-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("workshops", "0212_event_rq_jobs"),
        ("workshops", "0274_remove_event_rq_jobs"),
    ]

    dependencies = [
        ("workshops", "0211_task_rq_jobs"),
    ]

    operations = []
