# Generated by Django 2.2.9 on 2020-02-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemails', '0005_rqjob_scheduled_execution'),
        ('workshops', '0211_task_rq_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rq_jobs',
            field=models.ManyToManyField(blank=True, help_text='This should be filled out by AMY itself.', to='autoemails.RQJob', verbose_name='Related Redis Queue jobs'),
        ),
    ]
