# Generated by Django 2.2.10 on 2020-05-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0213_auto_20200501_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoprequest',
            name='online_inperson',
            field=models.CharField(default='', max_length=20, verbose_name='is this online or in person?'),
        ),
    ]
