# Generated by Django 2.2.10 on 2020-07-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0213_auto_20200501_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Additional people to contact'),
        ),
    ]
