# Generated by Django 2.2.13 on 2020-08-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0214_auto_20200713_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Family (last) name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Middle name'),
        ),
    ]
