# Generated by Django 2.2.13 on 2020-08-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0215_auto_20200808_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoprequest',
            name='instructor_availability',
            field=models.BooleanField(blank=True, default=False, verbose_name='I understand that if my workshop is less than two months away, The Carpentries can not guarantee availability of Instructors and I may not be able to hold my workshop as scheduled.'),
        ),
    ]
