# Generated by Django 2.2.13 on 2020-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0217_auto_20200615_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='registration_code',
            field=models.CharField(blank=True, help_text='Unique registration code used for Eventbrite and trainee application.', max_length=40, null=True, unique=True, verbose_name='Registration Code'),
        ),
    ]
