# Generated by Django 2.2.13 on 2020-08-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0217_auto_20200615_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoprequest',
            name='online_inperson',
            field=models.CharField(choices=[('online', 'Online'), ('inperson', 'In-person'), ('unsure', 'Not sure')], default='', max_length=15, verbose_name='Will this workshop be held online or in-person?'),
        ),
    ]
