# Generated by Django 2.2.13 on 2020-10-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0221_auto_20201025_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoprequest',
            name='rq_jobs',
            field=models.ManyToManyField(blank=True, help_text='This should be filled out by AMY itself.', to='autoemails.RQJob', verbose_name='Related Redis Queue jobs'),
        ),
    ]
