# Generated by Django 2.2.13 on 2020-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0220_event_public_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='data_privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html" target="_blank" rel="noreferrer">the data privacy policy</a> of The Carpentries.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='may_contact',
            field=models.BooleanField(default=True, help_text='Allow to contact from The Carpentries according to the <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html" target="_blank" rel="noreferrer">Privacy Policy</a>.'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='code_of_conduct_agreement',
            field=models.BooleanField(default=False, verbose_name='I agree to abide by The Carpentries\' <a href="https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html" target="_blank" rel="noreferrer">Code of Conduct</a>.'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='data_privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html" target="_blank" rel="noreferrer">the data privacy policy</a> of The Carpentries.'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='code_of_conduct_agreement',
            field=models.BooleanField(default=False, verbose_name='I agree to abide by The Carpentries\' <a href="https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html" target="_blank" rel="noreferrer">Code of Conduct</a>.'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='data_privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to <a href="https://docs.carpentries.org/topic_folders/policies/privacy.html" target="_blank" rel="noreferrer">the data privacy policy</a> of The Carpentries.'),
        ),
    ]
