# Generated by Django 2.2.17 on 2020-11-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0223_membership_agreement_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='invoice_status',
        ),
    ]
