# Generated by Django 2.2.17 on 2020-11-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0224_remove_event_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='admin_fee',
        ),
    ]
