# Generated by Django 2.2.13 on 2020-12-21 16:05

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0225_remove_event_admin_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Twitter username'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\-_]+$', flags=re.RegexFlag(256))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Required in order for this event to be "published".', max_length=350),
        ),
    ]
