# Generated by Django 2.2.17 on 2021-01-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0226_auto_20201221_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='agreement_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='agreement_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
