# Generated by Django 2.2.17 on 2021-02-20 20:24

from django.db import migrations, models


def create_membership_names(apps, schema_editor):
    """Create names for memberships out of their first organisation."""
    Membership = apps.get_model("workshops", "Membership")
    for membership in Membership.objects.prefetch_related("organizations"):
        org = membership.organizations.all()[0]
        membership.name = org.fullname
        membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0231_auto_20210217_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(create_membership_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
