# Generated by Django 2.2.17 on 2021-02-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0232_membership_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='extended',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days the agreement was extended with. If this value was provided, then the agreement end has been moved.', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='agreement_end',
            field=models.DateField(help_text='If an extension is being granted, do not manually edit the end date. Use the "Extend" button on membership details page instead.'),
        ),
    ]
