# Generated by Django 2.2.17 on 2021-02-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0233_membership_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='instructor_training_seats_rolled_from_previous',
            field=models.PositiveIntegerField(blank=True, help_text='Instructor training seats rolled over from previous membership.', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='instructor_training_seats_rolled_over',
            field=models.PositiveIntegerField(blank=True, help_text='Instructor training seats rolled over into next membership.', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='self_organized_workshops_rolled_from_previous',
            field=models.PositiveIntegerField(blank=True, help_text='Self-organized workshops rolled over from previous membership.', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='self_organized_workshops_rolled_over',
            field=models.PositiveIntegerField(blank=True, help_text='Self-organized workshops rolled over into next membership.', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='workshops_without_admin_fee_rolled_from_previous',
            field=models.PositiveIntegerField(blank=True, help_text='Workshops without admin fee rolled over from previous membership.', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='workshops_without_admin_fee_rolled_over',
            field=models.PositiveIntegerField(blank=True, help_text='Workshops without admin fee rolled over into next membership.', null=True),
        ),
    ]
