# Generated by Django 2.2.17 on 2021-03-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0235_remove_event_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
