# Generated by Django 2.2.18 on 2021-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0236_organization_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='review_process',
            field=models.CharField(choices=[('preapproved', 'Profile Creation for Pre-approved Trainees'), ('open', 'Open Training Application')], default='', max_length=20, verbose_name='Application Type'),
        ),
    ]
