# Generated by Django 2.2.17 on 2021-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0236_organization_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='seats_instructor_training',
            new_name='public_instructor_training_seats',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='additional_instructor_training_seats',
            new_name='additional_public_instructor_training_seats',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='instructor_training_seats_rolled_from_previous',
            new_name='public_instructor_training_seats_rolled_from_previous',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='instructor_training_seats_rolled_over',
            new_name='public_instructor_training_seats_rolled_over',
        ),
        migrations.AlterField(
            model_name='membership',
            name='public_instructor_training_seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of public seats in instructor trainings', verbose_name='Public instructor training seats'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='additional_public_instructor_training_seats',
            field=models.PositiveIntegerField(default=0, help_text='Use this field if you want to grant more public seats than the agreement provides for.', verbose_name='Additional public instructor training seats'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='public_instructor_training_seats_rolled_from_previous',
            field=models.PositiveIntegerField(blank=True, help_text='Public instructor training seats rolled over from previous membership.', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='public_instructor_training_seats_rolled_over',
            field=models.PositiveIntegerField(blank=True, help_text='Public instructor training seats rolled over into next membership.', null=True),
        ),
    ]
