# Generated by Django 2.2.17 on 2021-03-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0237_auto_20210321_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='seat_public',
            field=models.BooleanField(blank=True, choices=[(True, 'Public seat'), (False, 'In-house seat')], default=True, verbose_name='Count seat as public or in-house?', help_text='Ignored if the task is not for membership seat.'),
        ),
    ]
