# Generated by Django 2.2.18 on 2021-05-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0242_auto_20210503_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='affiliated_organizations',
            field=models.ManyToManyField(blank=True, related_name='_organization_affiliated_organizations_+', to='workshops.Organization'),
        ),
    ]
