# Generated by Django 2.2.24 on 2021-07-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0248_membership_rolled_to_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='variant',
            field=models.CharField(choices=[('partner', 'Partner'), ('affiliate', 'Affiliate'), ('sponsor', 'Sponsor'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('alacarte', 'A la carte')], max_length=40),
        ),
    ]
