# Generated by Django 2.2.24 on 2021-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemails', '0018_auto_20210811_1820'),
        ('workshops', '0249_auto_20210709_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rq_jobs',
            field=models.ManyToManyField(blank=True, help_text='This should be filled out by AMY itself.', to='autoemails.RQJob', verbose_name='Related Redis Queue jobs'),
        ),
    ]
