# Generated by Django 3.2.14 on 2022-08-07 10:19

from django.db import migrations

import workshops.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0252_auto_20211231_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='github',
            field=workshops.fields.NullableGithubUsernameField(blank=True, default='', help_text='Please put only a single username here. After your application has been accepted, you will be able to use your GitHub username to log in to our database to view your profile.', max_length=39, null=True, verbose_name='GitHub username'),
        ),
    ]
