# Generated by elichad on 2023-05-12 13:40

from django.db import migrations


def rename_discussion_to_welcome_session(apps, schema_editor) -> None:
    TrainingRequirement = apps.get_model("workshops", "TrainingRequirement")

    try:
        requirement = TrainingRequirement.objects.get(name="Discussion")
        requirement.name = "Welcome Session"
        requirement.save()
    except TrainingRequirement.DoesNotExist:
        pass


def rename_welcome_session_to_discussion(apps, schema_editor) -> None:
    TrainingRequirement = apps.get_model("workshops", "TrainingRequirement")

    try:
        requirement = TrainingRequirement.objects.get(name="Welcome Session")
        requirement.name = "Discussion"
        requirement.save()
    except TrainingRequirement.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [  # TODO: depend on 0258 evaluated by etc
        ("workshops", "0257_alter_membership_variant"),
    ]

    operations = [
        migrations.RunPython(
            rename_discussion_to_welcome_session,
            rename_welcome_session_to_discussion,
        )
    ]
