# Generated by Django 3.2.18 on 2023-05-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0257_alter_membership_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogress',
            name='evaluated_by',
        ),
    ]
