# Generated by Django 3.2.18 on 2023-05-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0258_remove_trainingprogress_evaluated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogress',
            name='discarded',
        ),
    ]
