# Generated by Django 3.2.19 on 2023-05-17 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("trainings", "0001_initial"),
        ("workshops", "0259_remove_deprecated_training_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingprogress",
            name="curriculum",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("carpentry", ""), _negated=True),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workshops.curriculum",
            ),
        ),
        migrations.AddField(
            model_name="trainingprogress",
            name="date",
            field=models.DateField(
                help_text="Only required when 'Type' is 'Get Involved'",
                blank=True,
                null=True,
                verbose_name="Date of occurrence",
            ),
        ),
        migrations.AddField(
            model_name="trainingprogress",
            name="involvement_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="trainings.involvement",
                verbose_name="Type of involvement (Get Involved only)",
            ),
        ),
        migrations.AddField(
            model_name="trainingrequirement",
            name="involvement_required",
            field=models.BooleanField(default=False),
        ),
    ]
