# Generated by Django 3.2.19 on 2023-05-26 12:29

from django.db import migrations


def rename_lesson_contribution_to_get_involved(apps, schema_editor) -> None:
    TrainingRequirement = apps.get_model("workshops", "TrainingRequirement")

    try:
        requirement = TrainingRequirement.objects.get(name="Lesson Contribution")
        requirement.name = "Get Involved"
        requirement.save()
    except TrainingRequirement.DoesNotExist:
        pass


def rename_get_involved_to_lesson_contribution(apps, schema_editor) -> None:
    TrainingRequirement = apps.get_model("workshops", "TrainingRequirement")

    try:
        requirement = TrainingRequirement.objects.get(name="Get Involved")
        requirement.name = "Lesson Contribution"
        requirement.save()
    except TrainingRequirement.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0260_add_involvement_types"),
    ]

    operations = [
        migrations.RunPython(
            rename_lesson_contribution_to_get_involved,
            rename_get_involved_to_lesson_contribution,
        )
    ]
