# Generated by Django 3.2.20 on 2023-08-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0262_alter_trainingrequest_training_completion_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoprequest',
            name='number_attendees',
        ),
    ]
