# Generated by Django 3.2.20 on 2023-10-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0265_add_member_affiliation_and_member_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingrequest',
            old_name='group_name',
            new_name='member_code',
        ),
    ]
