# Generated by Django 3.2.20 on 2023-10-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0266_rename_group_name_trainingrequest_member_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrequest",
            name="member_code_override",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="A member of our team will check the code and follow up with you if there are any problems that require your attention.",
                verbose_name="Continue with registration code marked as invalid",
            ),
        ),
    ]
