# Generated by Django 3.2.20 on 2023-10-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0267_trainingrequest_accept_invalid_member_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoprequest',
            name='member_affiliation',
        ),
    ]
