# Generated by Django 3.2.20 on 2023-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('workshops', '0269_alter_trainingrequest_nonprofit_teaching_experience'), ('workshops', '0270_auto_20231030_0919')]

    dependencies = [
        ('workshops', '0268_remove_workshoprequest_member_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='nonprofit_teaching_experience',
            field=models.CharField(blank=True, default='', help_text="Provide details or leave blank if this doesn't apply to you.", max_length=255, verbose_name='I have been an active contributor to other volunteer or non-profit groups with significant teaching or training components.'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='previous_experience_explanation',
            field=models.TextField(blank=True, default='', verbose_name='Description of your previous experience in teaching'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='previous_training_explanation',
            field=models.TextField(blank=True, default='', verbose_name='Description of your previous training in teaching'),
        ),
    ]
