# Generated by Django 4.2.13 on 2024-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0270_alter_organization_affiliated_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="open_CLDT_applications",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="If this event is <b>CLDT</b>, you can mark it as 'open applications' which means that people not associated with this event's member sites can also take part in this event.",
                verbose_name="CLDT Open applications",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="additional_cldt_seats",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Use this field if you want to grant more CLDT seats than the agreement provides for.",
                verbose_name="Additional CLDT seats",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="cldt_seats",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of CLDT seats",
                verbose_name="Collaborative Lesson Development Training seats",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="cldt_seats_rolled_from_previous",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="CLDT seats rolled over from previous membership.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="cldt_seats_rolled_over",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="CLDT seats rolled over into next membership.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="public_status",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="private",
                help_text="Public memberships may be listed on any of The Carpentries websites.",
                max_length=20,
                verbose_name="Can this membership be publicized on The Carpentries websites?",
            ),
        ),
    ]
