# Generated by Django 4.2.16 on 2024-12-30 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0271_alter_workshoprequest_administrative_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="host",
            field=models.ForeignKey(
                help_text="The institution where the workshop is taking place (or would take place for online workshops).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hosted_events",
                to="workshops.organization",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                help_text="The membership this workshop should count towards.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workshops.membership",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="sponsor",
            field=models.ForeignKey(
                help_text="The institution responsible for organizing and funding the workshop (often the same as Host).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sponsored_events",
                to="workshops.organization",
            ),
        ),
    ]
