# Generated by Django 4.2.13 on 2025-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0272_multiple_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="mastodon",
            field=models.URLField(
                blank=True, default="", verbose_name="Mastodon profile URL"
            ),
        ),
    ]
