# Generated by Django 4.2.19 on 2025-02-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0272_multiple_changes"),
        ("workshops", "0273_remove_task_rq_jobs"),
        ("workshops", "0274_remove_event_rq_jobs"),
        ("workshops", "0275_remove_workshoprequest_rq_jobs"),
        ("workshops", "0276_remove_person_rq_jobs"),
    ]

    operations = []
