# Generated by Django 4.2.20 on 2025-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0279_alter_trainingrequest_code_of_conduct_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mastodon',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Mastodon URL'),
        ),
    ]
