# Generated by Django 4.2.20 on 2025-07-02 19:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0280_person_mastodon"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("program_category", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
