# Generated by Django 4.2.20 on 2025-07-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0281_curriculumtype_eventcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="workshops.eventcategory"
            ),
        ),
    ]
