# Generated by Django 4.2.23 on 2025-09-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offering", "0002_benefit_credits_accountbenefitdiscount_accountbenefit"),
        ("workshops", "0282_event_event_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allocated_benefit",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to=models.Q(("benefit__unit_type", "event")),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="offering.accountbenefit",
                verbose_name="Allocated account benefit (of type 'event')",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="allocated_benefit",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to=models.Q(("benefit__unit_type", "seat")),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="offering.accountbenefit",
                verbose_name="Allocated account benefit (of type 'seat')",
            ),
        ),
    ]
