# Generated by Django 4.2.25 on 2025-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0285_person_airport_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="airport_country",
            field=models.CharField(
                default="", help_text="Airport country (copied from airport data package)", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="airport_lat",
            field=models.FloatField(default=0.0, help_text="Airport latitude (copied from airport data package)"),
        ),
        migrations.AddField(
            model_name="person",
            name="airport_lon",
            field=models.FloatField(default=0.0, help_text="Airport longitude (copied from airport data package)"),
        ),
    ]
