# Generated by Django 4.2.25 on 2025-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0286_person_airport_country_person_airport_lat_and_lon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="airport_country",
            field=models.CharField(
                blank=True, default="", help_text="Airport country (copied from airport data package)", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="airport_iata",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nearest major airport (IATA code: https://www.world-airport-codes.com/)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="trainingrequest",
            name="max_travelling_frequency",
            field=models.CharField(
                choices=[
                    ("not-at-all", "Not at all"),
                    ("yearly", "Once a year"),
                    ("often", "Several times a year"),
                    ("other", "Other:"),
                ],
                default="not-at-all",
                max_length=40,
                verbose_name="How frequently would you be able to travel to teach such classes?",
            ),
        ),
        migrations.AlterField(
            model_name="trainingrequest",
            name="previous_training",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("hours", "A few hours"),
                    ("workshop", "A workshop"),
                    ("course", "A certification or short course"),
                    ("full", "A full degree"),
                    ("other", "Other:"),
                ],
                default="none",
                max_length=40,
                verbose_name="Previous formal training as a teacher or instructor",
            ),
        ),
        migrations.AlterField(
            model_name="trainingrequest",
            name="teaching_frequency_expectation",
            field=models.CharField(
                choices=[
                    ("not-at-all", "Not at all"),
                    ("yearly", "Once a year"),
                    ("monthly", "Several times a year"),
                    ("other", "Other:"),
                ],
                default="not-at-all",
                max_length=40,
                verbose_name="How often would you expect to teach Carpentries workshops  (of any kind) "
                "after this training?",
            ),
        ),
    ]
