# Generated by Django 5.2.9 on 2025-12-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0286_alter_trainingrequest_max_travelling_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="badges",
            field=models.ManyToManyField(
                through="workshops.Award", through_fields=("person", "badge"), to="workshops.badge"
            ),
        ),
    ]
