# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  # If true, then any SSH connections made will enable agent forwarding.
  # config.ssh.forward_agent = true
  config.vm.synced_folder "..", "/vagrant_amy"
  config.vm.provision :shell, :path => "provision"
end
