# Generated by Django 2.1.7 on 2019-07-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0003_datavariant_selforganizedsubmission_workshopinquiryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopinquiryrequest',
            name='travel_expences_agreement',
            field=models.BooleanField(default=False, verbose_name='Regardless of the fee due to The Carpentries, I understand I am also responsible for travel costs for the Instructors which can include airfare, ground travel, hotel, and meals/incidentals. I understand local Instructors will be prioritized but not guaranteed. Instructor travel costs are managed directly between the host site and the Instructors, not through The Carpentries. I will share detailed information regarding policies and procedures for travel arrangements with instructors. All reimbursements will be completed within 60 days of the workshop.'),
        ),
        migrations.AlterField(
            model_name='selforganizedsubmission',
            name='institution_other_name',
            field=models.CharField(blank=True, default='', help_text="Please enter institution name if it's not on the list above.", max_length=255, verbose_name='If your institutional affiliation is not listed, please enter the name'),
        ),
        migrations.AlterField(
            model_name='selforganizedsubmission',
            name='public_event',
            field=models.CharField(choices=[('public', 'Yes, this workshop is open to the public'), ('closed', 'No, this is a closed event'), ('', 'Other:')], default=None, help_text='Many of our workshops restrict registration to learners from the hosting institution. If your workshop will be open to registrants outside of your institution please let us know below.', max_length=20, verbose_name='Is this workshop open to the public?'),
        ),
        migrations.AlterField(
            model_name='selforganizedsubmission',
            name='workshop_types',
            field=models.ManyToManyField(limit_choices_to={'active': True}, to='workshops.Curriculum', verbose_name='Which Carpentry workshop are you teaching?'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='administrative_fee',
            field=models.CharField(choices=[('nonprofit', 'I am with a government site, university, or other nonprofit. I understand the workshop fee of US$2500, and agree to follow through on The Carpentries invoicing process.'), ('forprofit', 'I am with a corporate or for-profit site. I understand The Carpentries staff will contact me about workshop fees. I will follow through on The Carpentries invoicing process for the agreed upon fee.'), ('member', 'I am with a Member Organisation so the workshop fee does not apply (Instructor travel costs will still apply).'), ('waiver', 'I am requesting a scholarship for the workshop fee (Instructor travel costs will still apply).')], default=None, max_length=20, verbose_name='Which of the following applies to your payment for the administrative fee?'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='institution_other_name',
            field=models.CharField(blank=True, default='', help_text="Please enter institution name if it's not on the list above.", max_length=255, verbose_name='If your institutional affiliation is not listed, please enter the name'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='language',
            field=models.ForeignKey(help_text='Our workshops are offered primarily in English, with a few of our lessons available in Spanish. While materials are mainly in English, we know it can be valuable to have an instructor who speaks the native language of the learners. We will attempt to locate Instructors speaking a particular language, but cannot guarantee the availability of non-English speaking Instructors.', on_delete=django.db.models.deletion.PROTECT, to='workshops.Language', verbose_name='What is the preferred language for the workshop?'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='number_attendees',
            field=models.CharField(choices=[('10-40', '10-40 (one room, two instructors)'), ('40-80', '40-80 (two rooms, four instructors)'), ('80-120', '80-120 (three rooms, six instructors)')], default=None, help_text="This number doesn't need to be precise, but will help us decide how many instructors your workshop will need. Each workshop must have at least two instructors.", max_length=15, verbose_name='Anticipated number of attendees'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='public_event',
            field=models.CharField(choices=[('public', 'Yes, this workshop is open to the public'), ('closed', 'No, this is a closed event'), ('', 'Other:')], default=None, help_text='Many of our workshops restrict registration to learners from the hosting institution. If your workshop will be open to registrants outside of your institution please let us know below.', max_length=20, verbose_name='Is this workshop open to the public?'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='travel_expences_management',
            field=models.CharField(choices=[('booked', 'Hotel and airfare will be booked by site; ground travel and meals/incidentals will be reimbursed within 60 days.'), ('reimbursed', 'All expenses will be booked by instructors and reimbursed within 60 days.'), ('', 'Other:')], default=None, max_length=20, verbose_name='How will you manage travel expenses for Carpentries Instructors?'),
        ),
    ]
