# Generated by Django 2.1.7 on 2019-08-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0006_migrate_workshop_requests_to_selforg_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selforganizedsubmission',
            name='host_responsibilities',
            field=models.BooleanField(default=False, verbose_name='I understand <a href="https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#host-checklist">the responsibilities of the workshop host</a>, including recruiting local helpers to support the workshop (1 helper for every 8-10 learners).'),
        ),
        migrations.AlterField(
            model_name='selforganizedsubmission',
            name='public_event',
            field=models.CharField(blank=True, choices=[('invite', 'This event is open to learners by invitation only.'), ('closed', 'This event is open to learners inside of my institution.'), ('public', 'This event is open to learners outside of my institution.'), ('other', 'Other:')], default='', help_text='Many of our workshops restrict registration to learners from the hosting institution. If your workshop will be open to registrants outside of your institution please let us know below.', max_length=20, verbose_name='Is this workshop open to the public?'),
        ),
        migrations.AlterField(
            model_name='selforganizedsubmission',
            name='workshop_types',
            field=models.ManyToManyField(limit_choices_to={'active': True}, to='workshops.Curriculum', verbose_name='Which Carpentries workshop are you teaching?'),
        ),
    ]
