# Generated by Django 2.1.7 on 2019-08-09 10:04

from django.db import migrations, models
import django.db.models.deletion


def migrate_travel_exp_management(apps, schema_editor):
    """Migrate options previously with no contents (displayed as "Other:")
    to a new contents ("other")."""
    WorkshopInquiryRequest = apps.get_model('extrequests',
                                            'WorkshopInquiryRequest')
    WorkshopInquiryRequest.objects.filter(travel_expences_management="") \
                                  .update(travel_expences_management="other")


def migrate_institutional_restrictions(apps, schema_editor):
    """Migrate options previously with no contents (displayed as "Other:")
    to a new contents ("other")."""
    WorkshopInquiryRequest = apps.get_model('extrequests',
                                            'WorkshopInquiryRequest')
    WorkshopInquiryRequest.objects.filter(institution_restrictions="") \
                                  .update(institution_restrictions="other")


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0007_auto_20190809_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='academic_levels',
            field=models.ManyToManyField(blank=True, help_text='If you know the academic level(s) of your attendees, indicate them here.', to='workshops.AcademicLevel', verbose_name="Attendees' academic level / career stage"),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='administrative_fee',
            field=models.CharField(blank=True, choices=[('nonprofit', 'I am with a government site, university, or other nonprofit. I understand the workshop fee of US$2500, and agree to follow through on The Carpentries invoicing process.'), ('forprofit', 'I am with a corporate or for-profit site. I understand The Carpentries staff will contact me about workshop fees. I will follow through on The Carpentries invoicing process for the agreed upon fee.'), ('member', 'I am with a Member Organisation so the workshop fee does not apply (Instructor travel costs will still apply).'), ('waiver', 'I am requesting a scholarship for the workshop fee (Instructor travel costs will still apply).')], default=None, max_length=20, null=True, verbose_name='Which of the following applies to your payment for the administrative fee?'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='audience_description',
            field=models.TextField(blank=True, verbose_name='Please describe your anticipated audience, including their experience, background, and goals'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='computing_levels',
            field=models.ManyToManyField(blank=True, help_text="Indicate the attendees' level of computing experience, if known. We will ask attendees to fill in a skills survey before the workshop, so this answer can be an approximation.", to='workshops.ComputingExperienceLevel', verbose_name="Attendees' level of computing experience"),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='domains',
            field=models.ManyToManyField(blank=True, help_text="The attendees' academic field(s) of study, if known.", to='workshops.KnowledgeDomain', verbose_name='Domains or topic of interest for target audience'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='host_responsibilities',
            field=models.BooleanField(default=False, verbose_name='I understand <a href="https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#host-checklist">the responsibilities of the workshop host</a>, including recruiting local helpers to support the workshop (1 helper for every 8-10 learners).'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Our workshops are offered primarily in English, with a few of our lessons available in Spanish. While materials are mainly in English, we know it can be valuable to have an instructor who speaks the native language of the learners. We will attempt to locate Instructors speaking a particular language, but cannot guarantee the availability of non-English speaking Instructors.', null=True, on_delete=django.db.models.deletion.PROTECT, to='workshops.Language', verbose_name='What is the preferred language for the workshop?'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='number_attendees',
            field=models.CharField(blank=True, choices=[('10-40', '10-40 (one room, two instructors)'), ('40-80', '40-80 (two rooms, four instructors)'), ('80-120', '80-120 (three rooms, six instructors)')], default=None, help_text="This number doesn't need to be precise, but will help us decide how many instructors your workshop will need. Each workshop must have at least two instructors.", max_length=15, null=True, verbose_name='Anticipated number of attendees'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='preferred_dates',
            field=models.DateField(blank=True, help_text='Our workshops typically run two full days. Please select your preferred first day for the workshop. If you do not have exact dates or are interested in an alternative schedule, please indicate so below. Because we need to coordinate with instructors, a minimum of 2-3 months lead time is required for workshop planning.', null=True, verbose_name='Preferred dates'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='public_event',
            field=models.CharField(blank=True, choices=[('invite', 'This event is open to learners by invitation only.'), ('closed', 'This event is open to learners inside of my institution.'), ('public', 'This event is open to learners outside of my institution.'), ('other', 'Other:')], default='', help_text='Many of our workshops restrict registration to learners from the hosting institution. If your workshop will be open to registrants outside of your institution please let us know below.', max_length=20, verbose_name='Is this workshop open to the public?'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='requested_workshop_types',
            field=models.ManyToManyField(blank=True, help_text='If your learners are new to programming and primarily interested in working with data, Data Carpentry is likely the best choice. If your learners are interested in learning more about programming, including version control and automation, Software Carpentry is likely the best match. If your learners are people working in library and information related roles interested in learning data and software skills, Library Carpentry is the best choice. Please visit the <a href="https://software-carpentry.org/lessons/">Software Carpentry lessons page</a>, <a href="http://www.datacarpentry.org/lessons/">Data Carpentry lessons page</a>, or the <a href="https://librarycarpentry.org/lessons/">Library Carpentry lessons page</a> for more information about any of our lessons. If you’re not sure and would like to discuss with us, please select the "Don\'t know yet" option below.', limit_choices_to={'active': True}, to='workshops.Curriculum', verbose_name='Which Carpentries workshop are you requesting?'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='routine_data',
            field=models.ManyToManyField(blank=True, to='extrequests.DataVariant', verbose_name='What kinds of data does your target audience routinely work with?'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='travel_expences_agreement',
            field=models.BooleanField(blank=True, default=False, verbose_name='Regardless of the fee due to The Carpentries, I understand I am also responsible for travel costs for the Instructors which can include airfare, ground travel, hotel, and meals/incidentals. I understand local Instructors will be prioritized but not guaranteed. Instructor travel costs are managed directly between the host site and the Instructors, not through The Carpentries. I will share detailed information regarding policies and procedures for travel arrangements with instructors. All reimbursements will be completed within 60 days of the workshop.'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='travel_expences_management',
            field=models.CharField(blank=True, choices=[('booked', 'Hotel and airfare will be booked by site; ground travel and meals/incidentals will be reimbursed within 60 days.'), ('reimbursed', 'All expenses will be booked by instructors and reimbursed within 60 days.'), ('other', 'Other:')], default='', max_length=20, verbose_name='How will you manage travel expenses for Carpentries Instructors?'),
        ),
        migrations.RunPython(migrate_travel_exp_management),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='institution_restrictions',
            field=models.CharField(blank=True, choices=[('no_restrictions', 'No restrictions'), ('other', 'Other:')], default='', max_length=20, verbose_name='Our instructors live, teach, and travel globally. We understand that institutions may have citizenship or other requirements for employees or volunteers who facilitate workshops. If your institution fits this description, please share your requirements or note that there are no restrictions.'),
        ),
        migrations.RunPython(migrate_institutional_restrictions),
    ]
