# Generated by Django 2.1.7 on 2019-08-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0008_auto_20190809_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selforganizedsubmission',
            name='public_event',
            field=models.CharField(choices=[('invite', 'This event is open to learners by invitation only.'), ('closed', 'This event is open to learners inside of my institution.'), ('public', 'This event is open to learners outside of my institution.'), ('other', 'Other:')], default='', help_text='Many of our workshops restrict registration to learners from the hosting institution. If your workshop will be open to registrants outside of your institution please let us know below.', max_length=20, verbose_name='Is this workshop open to the public?'),
        ),
    ]
