# Generated by Django 2.1.7 on 2019-08-18 07:40

from django.db import migrations, models


def migrate_workshop_format(apps, schema_editor):
    """Migrate options previously with no contents (displayed as "Other:")
    to a new contents ("other")."""
    SelfOrganizedSubmission = apps.get_model('extrequests',
                                             'SelfOrganizedSubmission')
    SelfOrganizedSubmission.objects.filter(workshop_format="") \
                                   .update(workshop_format="other")


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0009_auto_20190811_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selforganizedsubmission',
            name='workshop_format',
            field=models.CharField(choices=[('standard', 'Standard two-day Carpentries workshop'), ('short', 'Short session (less than two days)'), ('periodic', 'Modules taught over a period of time (several weeks, one semester, etc.)'), ('other', 'Other:')], default='', max_length=20, verbose_name='What is the format of this workshop?'),
        ),
        migrations.RunPython(migrate_workshop_format),
    ]
