# Generated by Django 2.1.7 on 2019-08-22 19:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0012_auto_20190822_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='selforganizedsubmission',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country'),
        ),
    ]
