# Generated by Django 2.1.7 on 2019-09-07 11:16

from django.db import migrations, models


def add_new_data_variant(apps, schema_editor):
    DataVariant = apps.get_model('extrequests', 'DataVariant')
    dv = "Library data (e.g. MARC, XML, RDF, JSON)"
    DataVariant.objects.create(name=dv, unknown=False)


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0014_auto_20190907_1113'),
    ]

    operations = [
        migrations.RunPython(add_new_data_variant),
    ]
