# Generated by Django 2.2.5 on 2019-09-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0015_auto_20190907_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='requested_workshop_types',
            field=models.ManyToManyField(blank=True, help_text='If your learners are new to programming and primarily interested in working with data, Data Carpentry is likely the best choice. If your learners are interested in learning more about programming, including version control and automation, Software Carpentry is likely the best match. If your learners are people working in library and information related roles interested in learning data and software skills, Library Carpentry is the best choice. Please visit the <a href="https://software-carpentry.org/lessons/">Software Carpentry lessons page</a>, <a href="http://www.datacarpentry.org/lessons/">Data Carpentry lessons page</a>, or the <a href="https://librarycarpentry.org/lessons/">Library Carpentry lessons page</a> for more information about any of our lessons. If you’re not sure and would like to discuss with us, please select the "Don\'t know yet" option below.<br class="mb-1">Check all that apply.', limit_choices_to={'active': True}, to='workshops.Curriculum', verbose_name='Which Carpentries workshop are you requesting?'),
        ),
    ]
