# Generated by Django 2.2.5 on 2019-09-13 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('workshops', '0202_merge_20190907_1955'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extrequests', '0016_auto_20190913_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelfOrganizedSubmission',
            new_name='SelfOrganisedSubmission',
        ),
        migrations.AlterModelOptions(
            name='selforganisedsubmission',
            options={'ordering': ['created_at'], 'verbose_name': 'Self-Organised Submission', 'verbose_name_plural': 'Self-Organised Submissions'},
        ),
    ]
