# Generated by Django 2.2.5 on 2019-12-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0017_auto_20190913_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='selforganisedsubmission',
            name='secondary_email',
            field=models.EmailField(blank=True, default='', help_text='This is an optional, secondary email address we can use to contact you.', max_length=254, verbose_name='Secondary email address'),
        ),
        migrations.AddField(
            model_name='workshopinquiryrequest',
            name='secondary_email',
            field=models.EmailField(blank=True, default='', help_text='This is an optional, secondary email address we can use to contact you.', max_length=254, verbose_name='Secondary email address'),
        ),
    ]
