# Generated by Django 2.2.13 on 2020-11-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0024_auto_20201025_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='selforganisedsubmission',
            name='workshop_listed',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='If selected "Yes", the workshop will be published on following websites: <a href="https://carpentries.org/">The Carpentries</a>, <a href="https://datacarpentry.org/">Data Carpentry</a>, <a href="https://software-carpentry.org/">Software Carpentry</a>, <a href="https://librarycarpentry.org/">Library Carpentry</a>.', verbose_name='Would you like to have this workshop listed on our websites?'),
        ),
        migrations.AddField(
            model_name='workshopinquiryrequest',
            name='workshop_listed',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='If selected "Yes", the workshop will be published on following websites: <a href="https://carpentries.org/">The Carpentries</a>, <a href="https://datacarpentry.org/">Data Carpentry</a>, <a href="https://software-carpentry.org/">Software Carpentry</a>, <a href="https://librarycarpentry.org/">Library Carpentry</a>.', verbose_name='Would you like to have this workshop listed on our websites?'),
        ),
    ]
