# Generated by Django 2.2.17 on 2020-11-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0026_auto_20201107_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='attendee_academic_levels',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='attendee_computing_levels',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='attendee_data_analysis_level',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='attendee_domains',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='language',
        ),
        migrations.RemoveField(
            model_name='eventsubmission',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='eventsubmission',
            name='event',
        ),
        migrations.DeleteModel(
            name='DCSelfOrganizedEventRequest',
        ),
        migrations.DeleteModel(
            name='EventRequest',
        ),
        migrations.DeleteModel(
            name='EventSubmission',
        ),
    ]
