# Generated by Django 2.2.17 on 2020-11-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0027_auto_20201122_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataAnalysisLevel',
        ),
        migrations.DeleteModel(
            name='DCWorkshopDomain',
        ),
        migrations.DeleteModel(
            name='DCWorkshopTopic',
        ),
    ]
