# Generated by Django 2.2.24 on 2021-08-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0028_auto_20201122_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selforganisedsubmission',
            name='workshop_url',
            field=models.URLField(blank=True, default='', help_text='Please share the link to the public-facing workshop website. If you are using our template, this is typically in the format of https://username.github.io/YYYY-MM-DD-sitename or https://username.github.io/YYYY-MM-DD-sitename-online. We do not need links to a separate registration page, GitHub repo, or any other related pages.', max_length=255, verbose_name='Please share your workshop URL'),
        ),
    ]
