# Generated by Django 4.2.3 on 2023-12-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extrequests", "0030_auto_20211231_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopinquiryrequest",
            name="user_notes",
            field=models.TextField(
                blank=True,
                help_text="Please share any other information to help ensure we can best support you in coordinating the event.",
                verbose_name="Is there any other information you would like to share with us?",
            ),
        ),
    ]
