# Generated by Django 3.2.20 on 2023-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0031_remove_workshopinquiryrequest_number_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='selforganisedsubmission',
            name='membership_affiliation',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='This may be the same as your institution above, or another institution.', verbose_name='Are you affiliated with a Carpentries member organization?'),
        ),
        migrations.AddField(
            model_name='selforganisedsubmission',
            name='membership_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name="Please enter the registration code for your organization's membership."),
        ),
        migrations.AddField(
            model_name='workshopinquiryrequest',
            name='membership_affiliation',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='This may be the same as your institution above, or another institution.', verbose_name='Are you affiliated with a Carpentries member organization?'),
        ),
        migrations.AddField(
            model_name='workshopinquiryrequest',
            name='membership_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name="Please enter the registration code for your organization's membership."),
        ),
    ]
