# Generated by Django 4.2.17 on 2025-01-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrequests", "0034_alter_workshopinquiryrequest_administrative_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopinquiryrequest",
            name="administrative_fee",
            field=models.CharField(
                choices=[
                    (
                        "nonprofit",
                        "I am with a government site, university, or other nonprofit. I understand the workshop fee as listed on The Carpentries website and agree to follow through on The Carpentries invoicing process.",
                    ),
                    (
                        "forprofit",
                        "I am with a corporate or for-profit site. I understand the costs for for-profit organisations are higher than the price for not-for-profit organisations, as listed on The Carpentries website.",
                    ),
                    (
                        "member",
                        "I am with a Member organisation so the workshop fee does not apply (instructor travel costs will still apply for in-person workshops).",
                    ),
                    (
                        "waiver",
                        "I am requesting financial support for the workshop fee (instructor travel costs will still apply for in-person workshops)",
                    ),
                ],
                default=None,
                help_text="<b><a href='https://carpentries.org/workshops/#workshop-cost' target='_blank' rel='noreferrer nofollow'>The Carpentries website workshop fee listing.</a></b>",
                max_length=20,
                verbose_name="Which of the following applies to your payment for the administrative fee?",
            ),
        ),
    ]
