# Generated by Django 4.2.20 on 2025-06-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0035_alter_workshopinquiryrequest_administrative_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selforganisedsubmission',
            name='code_of_conduct_agreement',
            field=models.BooleanField(default=False, verbose_name='I agree to abide by The Carpentries\' <a href="https://docs.carpentries.org/policies/coc/" target="_blank" rel="noreferrer">Code of Conduct</a>.'),
        ),
        migrations.AlterField(
            model_name='selforganisedsubmission',
            name='data_privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to <a href="https://docs.carpentries.org/policies/privacy.html" target="_blank" rel="noreferrer">the data privacy policy</a> of The Carpentries.'),
        ),
        migrations.AlterField(
            model_name='selforganisedsubmission',
            name='host_responsibilities',
            field=models.BooleanField(default=False, verbose_name="I understand <a href='https://docs.carpentries.org/resources/workshops/checklists.html'>the responsibilities of the workshop host</a>, including recruiting local helpers to support the workshop (1 helper for every 8-10 learners)."),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='code_of_conduct_agreement',
            field=models.BooleanField(default=False, verbose_name='I agree to abide by The Carpentries\' <a href="https://docs.carpentries.org/policies/coc/" target="_blank" rel="noreferrer">Code of Conduct</a>.'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='data_privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to <a href="https://docs.carpentries.org/policies/privacy.html" target="_blank" rel="noreferrer">the data privacy policy</a> of The Carpentries.'),
        ),
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='host_responsibilities',
            field=models.BooleanField(default=False, verbose_name="I understand <a href='https://docs.carpentries.org/resources/workshops/checklists.html'>the responsibilities of the workshop host</a>, including recruiting local helpers to support the workshop (1 helper for every 8-10 learners)."),
        ),
    ]
