# Generated by Django 2.1.2 on 2019-02-15 18:43

from django.db import migrations, models
import django_countries.fields


def add_initial_criteria(apps, schema_editor):
    """Add initial criteria."""

    Criterium = apps.get_model('dashboard', 'Criterium')
    data = [
        ('AU', 'admin-au@carpentries.org', 'AU'),
        ('Africa', 'admin-afr@carpentries.org',
         'DZ,AO,BJ,BW,BF,BI,CM,CV,CF,TD,KM,CD,DJ,EG,GQ,ER,ET,GA,GM,GH,GN,GW,'
         'CI,KE,LS,LR,LY,MG,MW,ML,MR,MU,YT,MA,MZ,NA,NE,NG,CG,RE,RW,SH,ST,SN,'
         'SC,SL,SO,ZA,SS,SD,SZ,TZ,TG,TN,UG,EH,ZM,ZW'),
        ('CA', 'admin-ca@carpentries.org', 'CA'),
        ('NZ', 'admin-nz@carpentries.org', 'NZ'),
        ('UK', 'admin-uk@carpentries.org', 'GB')
    ]
    for datum in data:
        name, email, countries = datum
        Criterium.objects.create(name=name, email=email, countries=countries)


def remove_initial_criteria(apps, schema_editor):
    """Remove initial criteria."""

    Criterium = apps.get_model('dashboard', 'Criterium')
    data = [
        ('AU', 'admin-au@carpentries.org'),
        ('Africa', 'admin-afr@carpentries.org'),
        ('CA', 'admin-ca@carpentries.org'),
        ('NZ', 'admin-nz@carpentries.org'),
        ('UK', 'admin-uk@carpentries.org')
    ]
    for datum in data:
        name, email = datum
        Criterium.filter(name=name, email=email).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('countries', django_countries.fields.CountryField(max_length=752, multiple=True, verbose_name='Countries to match this criterium')),
                ('email', models.EmailField(max_length=254, verbose_name='Notification email address')),
            ],
            options={
                'ordering': ['name', 'email'],
                'verbose_name': 'Notification Criterium',
                'verbose_name_plural': 'Notification Criteria'
            },
        ),
        migrations.RunPython(add_initial_criteria,  # forward
                             remove_initial_criteria),  # backward
    ]
