# Generated by Django 3.2.14 on 2022-09-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityroles', '0002_custom_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityroleconfig',
            name='autoassign_when_award_created',
            field=models.BooleanField(default=False, help_text='Should automatically assign a Community Role to a user, when a selected badge is awarded to them.', verbose_name='Auto-assign when award is created'),
        ),
    ]
