# Generated by Django 4.2.19 on 2025-02-06 05:29

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("consents", "0004_term_rq_jobs"),
        ("consents", "0010_remove_term_rq_jobs"),
    ]

    dependencies = [
        ("consents", "0003_term_help_text"),
    ]

    operations = []
