# Generated by Django 3.2.18 on 2023-04-05 10:56

from django.db import migrations, models

term_training_request_content = {
    "may-contact": (
        "The Carpentries will contact you about the progress of your application and,"
        " once certified, about teaching opportunities. May we also contact you for"
        " other volunteering opportunities, surveys, feedback, etc.?"
    ),
    "public-profile": (
        "The Carpentries will not make public any of your personal data when going"
        " through the application process. However, once certified, do you consent"
        " to your name and any linked social media accounts being published on The"
        " Carpentries website?"
    ),
}


def set_term_training_request_content(apps, schema_editor):
    Term = apps.get_model("consents", "Term")
    for slug, content in term_training_request_content.items():
        try:
            term = Term.objects.get(slug=slug)
            term.training_request_content = content
            term.save(update_fields=["training_request_content"])
        except Term.DoesNotExist:
            continue


class Migration(migrations.Migration):
    dependencies = [
        ("consents", "0008_trainingrequestconsent"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="training_request_content",
            field=models.TextField(
                help_text=(
                    "If set, the regular content will be replaced with this"
                    " text on the instructor training request form."
                ),
                blank=True,
                verbose_name="Content for Training Request Form",
            ),
        ),
        # set training request content for some specific terms
        migrations.RunPython(set_term_training_request_content, reverse_code=migrations.RunPython.noop),
    ]
