# Generated by Django 4.2.19 on 2025-02-06 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consents", "0004_term_rq_jobs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="term",
            name="rq_jobs",
        ),
    ]
