# Generated by Django 4.2.19 on 2025-02-06 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consents", "0009_term_training_request_content"),
        ("consents", "0010_remove_term_rq_jobs"),
    ]

    operations = []
