# Generated by Django 2.2.5 on 2019-09-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(help_text='It must be a unique name for this template.', max_length=255, unique=True, verbose_name='Template slug')),
                ('subject', models.CharField(blank=True, default='', help_text="Enter text for email subject. If you need to use loops, conditions, etc., use <a href='https://docs.djangoproject.com/en/dev/topics/templates/#the-django-template-language'>Django templates language</a>.", max_length=255)),
                ('to_header', models.CharField(blank=True, default='', help_text="Default value for 'To' field. It may be overridden by the email trigger. Use single address.", max_length=255, verbose_name='To')),
                ('from_header', models.CharField(blank=True, default='webmaster@localhost', help_text="Value for 'From' field. It defaults to application settings (currently 'webmaster@localhost') and may be overridden by the email trigger. Use single address.", max_length=255, verbose_name='From')),
                ('cc_header', models.CharField(blank=True, default='', help_text="Default value for 'CC' field. It may be overridden by the email trigger. Use single address.", max_length=255, verbose_name='CC')),
                ('bcc_header', models.CharField(blank=True, default='', help_text="Default value for 'BCC' field. It may be overridden by the email trigger. Use single address.", max_length=255, verbose_name='BCC')),
                ('reply_to_header', models.CharField(blank=True, default='', help_text="Default value for 'Reply-To' field. It may be overridden by the email trigger. Use single address.", max_length=255, verbose_name='Reply-To')),
                ('html_template', models.TextField(blank=True, default='', help_text="Enter HTML for email body. If you need to use loops, conditions, etc., use <a href='https://docs.djangoproject.com/en/dev/topics/templates/#the-django-template-language'>Django templates language</a>.", verbose_name='HTML body')),
                ('text_template', models.TextField(blank=True, default='', help_text="Enter plain text for email body. If you need to use loops, conditions, etc., use <a href='https://docs.djangoproject.com/en/dev/topics/templates/#the-django-template-language'>Django templates language</a>.", verbose_name='Plain text body')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
