# Generated by Django 2.2.5 on 2019-10-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoemails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(choices=[('new-instructor', 'Instructor is added to the workshop'), ('week-after-workshop-completion', '7 days past the end date of an active workshop')], max_length=50, verbose_name='Action')),
                ('template', models.OneToOneField(help_text='Select desired template. Only active templates are available. Each template can only be used once.', limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='autoemails.EmailTemplate', verbose_name='Template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
