# Generated by Django 2.2.5 on 2019-10-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemails', '0002_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='RQJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, verbose_name='RQ Job ID')),
                ('trigger', models.ForeignKey(on_delete=models.deletion.PROTECT, to='autoemails.Trigger', verbose_name='Trigger')),
            ],
        ),
        migrations.AddIndex(
            model_name='rqjob',
            index=models.Index(fields=['job_id'], name='autoemails__job_id_1bda65_idx'),
        ),
    ]
