# Generated by Django 2.2.5 on 2019-11-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoemails', '0003_rqjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rqjob',
            options={'verbose_name': 'RQ Job', 'verbose_name_plural': 'RQ Jobs'},
        ),
    ]
