# Generated by Django 2.2.9 on 2020-02-07 08:10

from django.db import migrations, models


def text_to_body(apps, schema_editor):
    EmailTemplate = apps.get_model('autoemails', 'EmailTemplate')
    EmailTemplate.objects.all().update(body_template=models.F('text_template'))


def body_to_text(apps, schema_editor):
    EmailTemplate = apps.get_model('autoemails', 'EmailTemplate')
    EmailTemplate.objects.all().update(text_template=models.F('body_template'))


class Migration(migrations.Migration):

    dependencies = [
        ('autoemails', '0005_rqjob_scheduled_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='body_template',
            field=models.TextField(blank=True, default='', help_text="Enter Markdown for email body. If you need to use loops, conditions, etc., use <a href='https://docs.djangoproject.com/en/dev/topics/templates/#the-django-template-language'>Django templates language</a>.", verbose_name='Markdown body'),
        ),
        migrations.RunPython(text_to_body, body_to_text),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='html_template',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='text_template',
        ),
    ]
