# Generated by Django 2.2.13 on 2020-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemails', '0013_auto_20200818_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='action',
            field=models.CharField(choices=[('new-instructor', 'Instructor is added to the workshop'), ('new-supporting-instructor', 'Supporting Instructor is added to the workshop'), ('week-after-workshop-completion', '7 days past the end date of an active workshop'), ('self-organised-request-form', 'A new event is created from Self-Organised Request Form'), ('instructors-host-introduction', 'Introduction of instrutors and host (centr. org. workshop)'), ('ask-for-website', 'Website URL is missing'), ('recruit-helpers', 'Recruit helpers'), ('workshop-request-response1', 'Response to Workshop Request 1'), ('workshop-request-response2', 'Response to Workshop Request 2'), ('workshop-request-response3', 'Response to Workshop Request 3')], max_length=50, verbose_name='Action'),
        ),
    ]
