# Generated by Django 2.2.17 on 2021-08-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemails', '0015_auto_20210405_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='action',
            field=models.CharField(choices=[('new-instructor', 'Instructor is added to the workshop'), ('new-supporting-instructor', 'Supporting Instructor is added to the workshop'), ('week-after-workshop-completion', '7 days past the end date of an active workshop'), ('self-organised-request-form', 'A new event is created from Self-Organised Request Form'), ('instructors-host-introduction', 'Introduction of instrutors and host (centr. org. workshop)'), ('ask-for-website', 'Website URL is missing'), ('recruit-helpers', 'Recruit helpers'), ('workshop-request-response1', 'Response to Workshop Request 1'), ('workshop-request-response2', 'Response to Workshop Request 2'), ('workshop-request-response3', 'Response to Workshop Request 3'), ('consent-required', 'There is a new or updated term added that the users should consent to'), ('archive-warning', 'Warning to the user to log in if they have not in a significant period of time')], max_length=50, verbose_name='Action'),
        ),
    ]
