# Generated by Django 2.2.24 on 2021-08-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemails', '0016_auto_20210809_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='rqjob',
            name='action_class',
            field=models.CharField(blank=True, default='', help_text='Action class that will be executed.', max_length=100, verbose_name='Action Class'),
        ),
        migrations.AddField(
            model_name='rqjob',
            name='interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Interval in seconds'),
        ),
        migrations.AddField(
            model_name='rqjob',
            name='result_ttl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Result TTL'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='action',
            field=models.CharField(choices=[('new-instructor', 'Instructor is added to the workshop'), ('new-supporting-instructor', 'Supporting Instructor is added to the workshop'), ('week-after-workshop-completion', '7 days past the end date of an active workshop'), ('self-organised-request-form', 'A new event is created from Self-Organised Request Form'), ('instructors-host-introduction', 'Introduction of instrutors and host (centr. org. workshop)'), ('ask-for-website', 'Website URL is missing'), ('recruit-helpers', 'Recruit helpers'), ('workshop-request-response1', 'Response to Workshop Request 1'), ('workshop-request-response2', 'Response to Workshop Request 2'), ('workshop-request-response3', 'Response to Workshop Request 3'), ('consent-required', 'There is a new or updated term added that the users should consent to'), ('profile-update', 'Reminder to for the user to update the information in their profile.')], max_length=50, verbose_name='Action'),
        ),
    ]
