# Generated by Django 2.2.24 on 2021-08-11 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoemails', '0017_auto_20210809_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='rqjob',
            name='interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Interval in seconds'),
        ),
        migrations.AddField(
            model_name='rqjob',
            name='result_ttl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Result TTL'),
        ),
        migrations.AlterField(
            model_name='rqjob',
            name='recipients',
            field=models.TextField(blank=True, default='', verbose_name='Mail recipients'),
        ),
        migrations.CreateModel(
            name='EmailReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('remind_again_date', models.DateTimeField()),
                ('number_times_sent', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoemails.Trigger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
