# Generated by Django 2.2.24 on 2022-01-03 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoemails', '0017_auto_20210901_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='action',
            field=models.CharField(choices=[('new-instructor', 'Instructor is added to the workshop'), ('new-supporting-instructor', 'Supporting Instructor is added to the workshop'), ('week-after-workshop-completion', '7 days past the end date of an active workshop'), ('self-organised-request-form', 'A new event is created from Self-Organised Request Form'), ('instructors-host-introduction', 'Introduction of instrutors and host (centr. org. workshop)'), ('ask-for-website', 'Website URL is missing'), ('recruit-helpers', 'Recruit helpers'), ('workshop-request-response1', 'Response to Workshop Request 1'), ('workshop-request-response2', 'Response to Workshop Request 2'), ('workshop-request-response3', 'Response to Workshop Request 3'), ('consent-required', 'There is a new or updated term added that the users should consent to'), ('profile-update', 'Reminder to for the user to update the information in their profile.'), ('profile-archival-warning-inactivity', 'Warning for the user to login before their profile will be archived due to inactivity.'), ('profile-archival-warning-consents', 'Warning for the user to login before their profile will be archived due to new consents they have not yet agreed to.')], max_length=50, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='EmailReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('remind_again_date', models.DateTimeField()),
                ('number_times_sent', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoemails.Trigger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
