# Generated by Django 2.2.24 on 2021-08-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemails', '0017_auto_20210809_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='rqjob',
            name='interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in seconds between function calls'),
        ),
        migrations.AddField(
            model_name='rqjob',
            name='result_ttl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Result TTL'),
        ),
    ]
