# Generated by Django 3.2.23 on 2023-12-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0004_scheduledemaillog_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledemail",
            name="context_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scheduledemail",
            name="to_header_context_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
