# Generated by Django 4.2.20 on 2025-07-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consortium",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
