# Generated by Django 4.2.23 on 2025-08-31 18:27

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0282_event_event_category"),
        ("fiscal", "0001_initial"),
        ("offering", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consortium",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("organisations", models.ManyToManyField(to="workshops.organization")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartnershipTier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("credits", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Partnership",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("credits", models.IntegerField()),
                ("agreement_start", models.DateField()),
                (
                    "agreement_end",
                    models.DateField(
                        help_text="If an extension is being granted, do not manually edit the end date. Use the "
                        '"Extend" button on partnership details page instead.'
                    ),
                ),
                (
                    "extensions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        default=list,
                        help_text="Number of days the agreement was extended. The field stores multiple extensions. "
                        "The agreement end date has been moved by a cumulative number of days from this field.",
                        size=None,
                    ),
                ),
                (
                    "agreement_link",
                    models.URLField(
                        default="",
                        help_text="Link to partnership agreement document or folder in Google Drive",
                        verbose_name="Link to partnership agreement",
                    ),
                ),
                (
                    "registration_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique registration code used for Eventbrite and trainee application.",
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Registration Code",
                    ),
                ),
                (
                    "public_status",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        help_text="Public partnerships may be listed on any of The Carpentries websites.",
                        max_length=20,
                        verbose_name="Can this partnership be publicized on The carpentries websites?",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Field that helps in some calculations, e.g. credits used.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="offering.account",
                    ),
                ),
                (
                    "partner_consortium",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only consortium or organisation can be selected, never both.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fiscal.consortium",
                    ),
                ),
                (
                    "partner_organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only consortium or organisation can be selected, never both.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workshops.organization",
                    ),
                ),
                (
                    "rolled_to_partnership",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rolled_from_partnership",
                        to="fiscal.partnership",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fiscal.partnershiptier"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="partnership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("partner_consortium__isnull", True), ("partner_organisation__isnull", True), _connector="XOR"
                ),
                name="check_only_one_partner",
                violation_error_message="Select only partner consortium OR partner organisation, never both.",
            ),
        ),
    ]
