# Generated by Django 4.2.23 on 2025-09-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0282_event_event_category"),
        ("fiscal", "0002_consortium_partnershiptier_partnership_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="partnership",
            name="check_only_one_partner",
        ),
        migrations.AlterField(
            model_name="partnership",
            name="partner_consortium",
            field=models.ForeignKey(
                blank=True,
                help_text="Only consortium or organisation can be selected, never both.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fiscal.consortium",
            ),
        ),
        migrations.AlterField(
            model_name="partnership",
            name="partner_organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="Only consortium or organisation can be selected, never both.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workshops.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnership",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("partner_consortium__isnull", True), ("partner_organisation__isnull", True), _connector="XOR"
                ),
                name="check_only_one_partner",
                violation_error_message="Select only partner consortium OR partner organisation, never both.",
            ),
        ),
    ]
