# Generated by Django 4.2.25 on 2025-11-30 16:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0002_consortium_partnershiptier_partnership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnership",
            name="credits_extensions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                default=list,
                help_text=(
                    "Number of credits extended. The field stores multiple extensions. "
                    "The credits value has been moved by a cumulative sum of values from this field."
                ),
                size=None,
            ),
        ),
    ]
