# Generated by Django 4.2.20 on 2025-08-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0002_consortium"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partnership",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("agreement_start", models.DateField()),
                (
                    "agreement_end",
                    models.DateField(
                        help_text="If an extension is being granted, do not manually edit the end date. Use the "
                        '"Extend" button on membership details page instead.'
                    ),
                ),
            ],
        ),
    ]
