# Generated by Django 4.2.23 on 2025-09-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0003_remove_partnership_check_only_one_partner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnership",
            name="credits",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partnershiptier",
            name="credits",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
