# Generated by Django 5.2.9 on 2026-01-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiscal", "0003_partnership_credits_extensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnership",
            name="registration_code",
            field=models.CharField(
                help_text="Unique registration code used for Eventbrite and trainee application.",
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Registration Code",
            ),
        ),
    ]
