# Generated by Django 5.2.9 on 2026-01-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiscal", "0004_alter_partnership_registration_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnership",
            name="tier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="fiscal.partnershiptier"
            ),
        ),
    ]
