# Generated by Django 5.2.12 on 2026-03-22 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiscal", "0005_alter_partnership_tier"),
        ("offering", "0007_alter_accountbenefit_registration_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnership",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offering.accountbenefitdiscount",
            ),
        ),
    ]
