# Generated by Django 5.2.12 on 2026-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiscal", "0006_partnership_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnershiptier",
            name="is_custom",
            field=models.BooleanField(
                default=False,
                help_text="If set, credits value can be customized per partnership instead of using the tier default.",
            ),
        ),
    ]
