# CI/CD for main branch

name: CI/CD (main - no deployment)

on:
  push:
    branches: [ main ]

jobs:
  accessibility:
    uses: ./.github/workflows/incl_accessibility.yml

  lint:
    uses: ./.github/workflows/incl_linter.yml

  test:
    uses: ./.github/workflows/incl_test.yml
    needs: lint
