# CI/CD for main branch

name: CI/CD (main)

on:
  push:
    branches: [ main ]

jobs:
  accessibility:
    uses: ./.github/workflows/include/accessibility.yml

  lint:
    uses: ./.github/workflows/include/linter.yml

  test:
    uses: ./.github/workflows/include/test.yml
    needs: lint
