# CI/CD for develop branch

name: CI/CD (develop)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    name: Build Docker image and push to ECR
    needs: test
    environment: staging
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ secrets.AWS_ECR_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AMY_ECR_REPO_NAME }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA -f docker/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA

