# CI/CD for develop branch

name: CI/CD (develop)

on:
  push:
    branches: [ develop ]

jobs:
  accessibility:
    uses: ./.github/workflows/incl_accessibility.yml

  lint:
    uses: ./.github/workflows/incl_linter.yml

  test:
    uses: ./.github/workflows/incl_test.yml
    needs: lint

  build_deploy:
    needs: test
    environment: staging
    uses: ./.github/workflows/incl_build_and_deploy.yml
