# CI/CD for develop branch

name: CI/CD (develop)

on:
  push:
    branches: [ develop ]

jobs:
  accessibility:
    uses: ./.github/workflows/include/accessibility.yml

  lint:
    uses: ./.github/workflows/include/linter.yml

  test:
    uses: ./.github/workflows/include/test.yml
    needs: lint

  build_deploy:
    needs: test
    environment: staging
    uses: ./.github/workflows/include/build_and_deploy.yml
