# CI/CD for main branch - contains only test runs

name: CI/CD (main)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, 'feature/**' ]

jobs:
  test:
    uses: ./.github/workflows/test.yml
